[install]
minimumReleaseAge = 604800
minimumReleaseAgeExcludes = ["brace-expansion", "esbuild", "fast-uri", "form-data", "ip-address", "js-cookie", "nanoid", "react", "react-dom", "react-server-dom-webpack", "socket.io-parser", "tmp", "undici"]
