/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 79c9da54f8989a09bf349e7ecdbf5108)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface DevEnv {
		ASSETS: Fetcher;
		VITE_PIRATE_API_BASE_URL: "https://api-dev.example.com";
		VITE_PRIVY_APP_ID: "";
		VITE_IPFS_GATEWAY_URL: "https://psc.myfilebase.com/ipfs";
	}
	interface StagingEnv {
		ASSETS: Fetcher;
		VITE_PIRATE_API_BASE_URL: "https://api-staging.pirate.sc";
		VITE_PRIVY_APP_ID: "cmnbdx9xk00ty0clapn2q8pdj";
		VITE_IPFS_GATEWAY_URL: "https://psc.myfilebase.com/ipfs";
	}
	interface Env {
		ASSETS: Fetcher;
		VITE_PIRATE_API_BASE_URL: "https://api-dev.example.com" | "https://api-staging.pirate.sc" | "https://api.example.com";
		VITE_PRIVY_APP_ID: "" | "cmnbdx9xk00ty0clapn2q8pdj";
		VITE_IPFS_GATEWAY_URL: "https://psc.myfilebase.com/ipfs";
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "VITE_PIRATE_API_BASE_URL" | "VITE_PRIVY_APP_ID" | "VITE_IPFS_GATEWAY_URL">> {}
}
