/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 0e1eac69eb7555a2f2e8bd290e480a71)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface StagingEnv {
		ASSETS: Fetcher;
		DEPLOY_ENV: "staging";
		NODE_ENV: "production";
	}
	interface Env {
		ASSETS: Fetcher;
		DEPLOY_ENV: "staging" | "production";
		NODE_ENV: "production";
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEPLOY_ENV" | "NODE_ENV">> {}
}
