/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 2bdbd14349cb101cf1c11a7941ebd572)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface StagingEnv {
		ASSETS: Fetcher;
		DEPLOY_ENV: "staging";
		HNS_FORWARDER_MAX_CLOCK_SKEW_SECONDS: "300";
		HNS_FORWARDER_TRUSTED_IPS: "94.103.168.161";
		NODE_ENV: "production";
	}
	interface Env {
		ASSETS: Fetcher;
		DEPLOY_ENV: "staging" | "production";
		HNS_FORWARDER_MAX_CLOCK_SKEW_SECONDS: "300";
		HNS_FORWARDER_TRUSTED_IPS: "94.103.168.161";
		NODE_ENV: "production";
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEPLOY_ENV" | "HNS_FORWARDER_MAX_CLOCK_SKEW_SECONDS" | "HNS_FORWARDER_TRUSTED_IPS" | "NODE_ENV">> {}
}
