// This file is generated by `bun run locales:generate`. Do not edit manually.

export const REAL_LOCALE_CODES = ["en","ar"] as const;
export const LOCALE_NAMESPACES = ["routes","shell"] as const;

export const GENERATED_LOCALE_CATALOGS = {
  "en": {
    "routes": {
      "common": {
        "backHome": "Back Home",
        "bestTab": "Best",
        "commentsHeading": "Comments",
        "createAction": "Create",
        "cancelReply": "Cancel",
        "joinedStatLabel": "Joined",
        "loadMoreReplies": "Load more replies",
        "loadReplies": "Load replies",
        "loadingReplies": "Loading replies...",
        "newTab": "New",
        "noComments": "No comments yet.",
        "replyAction": "Reply",
        "replyPlaceholder": "Write a reply",
        "showOriginal": "Show original",
        "showTranslation": "Show translation",
        "submitReply": "Post reply",
        "topAll": "All time",
        "topDay": "Today",
        "topHour": "This hour",
        "topMonth": "This month",
        "topTab": "Top",
        "topWeek": "This week",
        "topYear": "This year"
      },
      "home": {
        "membersLabel": "{count} members",
        "railTitle": "Recent posts",
        "subtitle": "",
        "title": "Home"
      },
      "yourCommunities": {
        "gatedLabel": "Gated",
        "openLabel": "Open",
        "railTitle": "Your Spaces",
        "subtitle": "A member-scoped feed shell. Keep it tight on mobile and let the sidebar carry the heavier navigation.",
        "title": "Your Communities"
      },
      "post": {
        "commentsBody": "Thread replies are not scaffolded yet. This route exists to pin the URL contract and page chrome for `post_id` reads.",
        "description": "Single-thread route shell for the future `GET /posts/{post_id}` read.",
        "fallbackTitle": "Post"
      },
      "onboarding": {
        "chooseNameAction": "Choose Name",
        "description": "Single onboarding route with client-managed phases. No nested onboarding URLs are locked yet.",
        "importKarmaAction": "Import Karma",
        "suggestedCommunitiesAction": "Suggested Communities",
        "title": "Finish setting up your Pirate identity"
      },
      "inbox": {
        "body": "Keep `/inbox` as a neutral placeholder until notifications or messaging are specified as real product surfaces.",
        "description": "This route is scaffolded so the mobile nav can point somewhere truthful while inbox behavior is still undefined.",
        "title": "Inbox placeholder"
      },
      "createCommunity": {
        "description": "Scaffolded shell around the existing community composer composition. Submission is not wired yet.",
        "title": "Create a community"
      },
      "notFound": {
        "body": "The first scaffold only locks a small set of routes: home, feeds, communities, posts, profiles, onboarding, inbox placeholder, and community create.",
        "description": "No scaffolded page exists for {path}.",
        "title": "Route not found"
      }
    },
    "shell": {
      "appHeader": {
        "connectLabel": "Connect",
        "createEmptyLabel": "No recent communities.",
        "createLabel": "Create",
        "createPickerTitle": "Create post in",
        "homeAriaLabel": "Go to home",
        "notificationsAriaLabel": "Notifications",
        "openNavigationAriaLabel": "Open navigation",
        "profileAriaLabel": "Open profile",
        "searchAriaLabel": "Search Pirate",
        "searchPlaceholder": "Search Pirate",
        "searchUnavailableToast": "Search is not scaffolded yet."
      },
      "appSidebar": {
        "brandLabel": "Pirate",
        "createCommunityLabel": "Create Community",
        "homeAriaLabel": "Go to home",
        "homeLabel": "Home",
        "resourcesLabel": "Resources",
        "sections": [
          {
            "id": "recent",
            "label": "Recent",
            "items": [
              {
                "id": "c/club1",
                "label": "c/club1"
              },
              {
                "id": "c/pirate-radio",
                "label": "c/pirate-radio"
              }
            ]
          },
          {
            "id": "communities",
            "label": "Communities",
            "items": [
              {
                "id": "c/builders",
                "label": "c/builders"
              },
              {
                "id": "c/mixes",
                "label": "c/mixes"
              },
              {
                "id": "c/samples",
                "label": "c/samples"
              }
            ]
          }
        ],
        "resourceItems": [
          {
            "id": "blog",
            "label": "Blog"
          },
          {
            "id": "terms-of-service",
            "label": "Terms of Service"
          },
          {
            "id": "privacy-policy",
            "label": "Privacy Policy"
          }
        ],
        "yourCommunitiesLabel": "Your Communities"
      },
      "mobileFooter": {
        "createLabel": "Create",
        "homeLabel": "Home",
        "inboxAriaLabel": "Inbox",
        "inboxLabel": "Inbox",
        "primaryNavAriaLabel": "Primary",
        "profileAriaLabel": "Profile",
        "profileLabel": "Profile"
      },
      "storybook": {
        "contentAreaLabel": "Content area",
        "desktopHeaderBody": "Header is standalone. Compose it into the real app shell, not into onboarding cards.",
        "mobileHeaderBody": "Mobile header only.",
        "mobileFooterBody": "Mobile footer only.",
        "mobileChromeLead": "Standalone shell chrome preview.",
        "mobileChromeFollow": "Header and footer stay reusable and separate from onboarding.",
        "standaloneDesktopSearchPlaceholder": "Find anything"
      }
    }
  },
  "ar": {
    "routes": {
      "common": {
        "backHome": "العودة إلى الرئيسية",
        "bestTab": "الأفضل",
        "commentsHeading": "التعليقات",
        "createAction": "أنشئ",
        "cancelReply": "إلغاء",
        "joinedStatLabel": "انضم",
        "loadMoreReplies": "حمّل المزيد من الردود",
        "loadReplies": "حمّل الردود",
        "loadingReplies": "جارٍ تحميل الردود...",
        "newTab": "الجديد",
        "noComments": "لا توجد تعليقات بعد.",
        "replyAction": "رد",
        "replyPlaceholder": "اكتب ردًا",
        "showOriginal": "أظهر الأصل",
        "showTranslation": "أظهر الترجمة",
        "submitReply": "انشر الرد",
        "topAll": "كل الوقت",
        "topDay": "اليوم",
        "topHour": "هذه الساعة",
        "topMonth": "هذا الشهر",
        "topTab": "الأعلى",
        "topWeek": "هذا الأسبوع",
        "topYear": "هذا العام"
      },
      "home": {
        "membersLabel": "{count} عضو",
        "railTitle": "المنشورات الحديثة",
        "subtitle": "",
        "title": "الرئيسية"
      },
      "yourCommunities": {
        "gatedLabel": "مغلق",
        "openLabel": "مفتوح",
        "railTitle": "مساحاتك",
        "subtitle": "خلاصة مخصّصة للأعضاء. أبقِها مركّزة على الهاتف ودع الشريط الجانبي يتحمّل التنقل الأثقل.",
        "title": "مجتمعاتك"
      },
      "post": {
        "commentsBody": "ردود السلسلة غير مهيأة بعد. هذا المسار موجود لتثبيت عقد عنوان URL وهيكل الصفحة لقراءات `post_id`.",
        "description": "هيكل مسار لسلسلة مفردة لقراءة `GET /posts/{post_id}` مستقبلًا.",
        "fallbackTitle": "منشور"
      },
      "onboarding": {
        "chooseNameAction": "اختر الاسم",
        "description": "مسار إعداد واحد بمراحل تُدار من العميل. لم يتم تثبيت عناوين URL المتداخلة للإعداد بعد.",
        "importKarmaAction": "استورد الكارما",
        "suggestedCommunitiesAction": "مجتمعات مقترحة",
        "title": "أكمل إعداد هوية Pirate الخاصة بك"
      },
      "inbox": {
        "body": "أبقِ `/inbox` كعنصر نائب محايد حتى يتم تحديد الإشعارات أو المراسلة كسطوح منتج حقيقية.",
        "description": "تم تجهيز هذا المسار حتى يشير إليه تنقل الهاتف بصدق بينما لا يزال سلوك الوارد غير محدد.",
        "title": "عنصر نائب للوارد"
      },
      "createCommunity": {
        "description": "هيكل جاهز حول مكوّن إنشاء المجتمع الحالي. الإرسال غير موصول بعد.",
        "title": "أنشئ مجتمعًا"
      },
      "notFound": {
        "body": "النسخة الأولى من الهيكل تثبّت فقط مجموعة صغيرة من المسارات: الرئيسية، الخلاصات، المجتمعات، المنشورات، الملفات الشخصية، الإعداد، عنصر نائب للوارد، وإنشاء مجتمع.",
        "description": "لا توجد صفحة مجهزة للمسار {path}.",
        "title": "المسار غير موجود"
      }
    },
    "shell": {
      "appHeader": {
        "connectLabel": "اتصل",
        "createEmptyLabel": "لا توجد مجتمعات حديثة.",
        "createLabel": "أنشئ",
        "createPickerTitle": "أنشئ منشورًا في",
        "homeAriaLabel": "اذهب إلى الصفحة الرئيسية",
        "notificationsAriaLabel": "الإشعارات",
        "openNavigationAriaLabel": "افتح التنقل",
        "profileAriaLabel": "افتح الملف الشخصي",
        "searchAriaLabel": "ابحث في بايرت",
        "searchPlaceholder": "ابحث في Pirate",
        "searchUnavailableToast": "البحث غير متاح بعد."
      },
      "appSidebar": {
        "brandLabel": "Pirate",
        "createCommunityLabel": "أنشئ مجتمعًا",
        "homeAriaLabel": "اذهب إلى الصفحة الرئيسية",
        "homeLabel": "الرئيسية",
        "resourcesLabel": "الموارد",
        "sections": [
          {
            "id": "recent",
            "label": "الأخيرة",
            "items": [
              {
                "id": "c/club1",
                "label": "c/النادي-١"
              },
              {
                "id": "c/pirate-radio",
                "label": "c/راديو-بايرت"
              }
            ]
          },
          {
            "id": "communities",
            "label": "المجتمعات",
            "items": [
              {
                "id": "c/builders",
                "label": "c/البناؤون"
              },
              {
                "id": "c/mixes",
                "label": "c/الميكسات"
              },
              {
                "id": "c/samples",
                "label": "c/السامبلز"
              }
            ]
          }
        ],
        "resourceItems": [
          {
            "id": "blog",
            "label": "المدونة"
          },
          {
            "id": "terms-of-service",
            "label": "شروط الخدمة"
          },
          {
            "id": "privacy-policy",
            "label": "سياسة الخصوصية"
          }
        ],
        "yourCommunitiesLabel": "مجتمعاتك"
      },
      "mobileFooter": {
        "createLabel": "أنشئ",
        "homeLabel": "الرئيسية",
        "inboxAriaLabel": "الوارد",
        "inboxLabel": "الوارد",
        "primaryNavAriaLabel": "التنقل الرئيسي",
        "profileAriaLabel": "الملف الشخصي",
        "profileLabel": "الملف الشخصي"
      },
      "storybook": {
        "contentAreaLabel": "منطقة المحتوى",
        "desktopHeaderBody": "الهيدر مستقل. كوّنه داخل غلاف التطبيق الحقيقي، وليس داخل بطاقات الإعداد.",
        "mobileHeaderBody": "الهيدر المحمول فقط.",
        "mobileFooterBody": "التذييل المحمول فقط.",
        "mobileChromeLead": "معاينة مستقلة لكروم التطبيق.",
        "mobileChromeFollow": "يبقى الهيدر والتذييل قابلين لإعادة الاستخدام ومنفصلين عن بطاقات الإعداد.",
        "standaloneDesktopSearchPlaceholder": "ابحث عن أي شيء"
      }
    }
  }
} as const;

export type RealLocaleCode = (typeof REAL_LOCALE_CODES)[number];
export type LocaleNamespace = (typeof LOCALE_NAMESPACES)[number];
export type GeneratedLocaleCatalogs = typeof GENERATED_LOCALE_CATALOGS;
