// This file is generated by `bun run locales:generate`. Do not edit manually.

export const REAL_LOCALE_CODES = ["en","ar"] as const;
export const LOCALE_NAMESPACES = ["routes","shell"] as const;

export const GENERATED_LOCALE_CATALOGS = {
  "en": {
    "routes": {
      "common": {
        "backHome": "Back Home",
        "bestTab": "Best",
        "commentsHeading": "Comments",
        "createAction": "Create",
        "joinedStatLabel": "Joined",
        "newTab": "New",
        "topAll": "All time",
        "topDay": "Today",
        "topHour": "This hour",
        "topMonth": "This month",
        "topTab": "Top",
        "topWeek": "This week",
        "topYear": "This year"
      },
      "home": {
        "membersLabel": "{count} members",
        "railTitle": "Recent posts",
        "subtitle": "",
        "title": "Home"
      },
      "yourCommunities": {
        "gatedLabel": "Gated",
        "openLabel": "Open",
        "railTitle": "Your Spaces",
        "subtitle": "A member-scoped feed shell. Keep it tight on mobile and let the sidebar carry the heavier navigation.",
        "title": "Your Communities"
      },
      "post": {
        "commentsBody": "Replies are not loaded in this web build yet.",
        "description": "Live post view for `GET /posts/{post_id}` records.",
        "fallbackTitle": "Post"
      },
      "onboarding": {
        "chooseNameAction": "Username",
        "description": "Three-step onboarding route for Reddit verification, handle selection, and community suggestions.",
        "importKarmaAction": "Reddit",
        "suggestedCommunitiesAction": "Communities",
        "title": "Finish setting up your Pirate identity"
      },
      "auth": {
        "body": "Sign in to create or resume a Pirate browser session. Once connected, this page shows your current account and onboarding status.",
        "description": "Account entry point for browser sign-in, session state, and verification routing.",
        "title": "Account"
      },
      "authDevice": {
        "description": "Browser handoff route for terminal or device login. The page signs in with Privy, checks onboarding, and authorizes the waiting device session.",
        "title": "Device auth"
      },
      "inbox": {
        "body": "Use this page to inspect your current browser session, verification state, and onboarding readiness.",
        "description": "Account-scoped status surface for verification, onboarding, and system events.",
        "title": "Inbox"
      },
      "createCommunity": {
        "description": "Namespace-backed community creation flow with live account verification and submission wiring.",
        "title": "Create a community"
      },
      "notFound": {
        "body": "The current web shell covers home, feeds, communities, posts, profiles, onboarding, account, inbox, and community creation.",
        "description": "No scaffolded page exists for {path}.",
        "title": "Route not found"
      }
    },
    "shell": {
      "appHeader": {
        "connectLabel": "Connect",
        "createLabel": "Create",
        "homeAriaLabel": "Go to home",
        "notificationsAriaLabel": "Notifications",
        "openNavigationAriaLabel": "Open navigation",
        "profileAriaLabel": "Open profile",
        "searchAriaLabel": "Search Pirate",
        "searchPlaceholder": "Search Pirate",
        "searchUnavailableToast": "Search is not scaffolded yet.",
        "verifyLabel": "Verify"
      },
      "appSidebar": {
        "brandLabel": "Pirate",
        "createCommunityLabel": "Create Community",
        "homeAriaLabel": "Go to home",
        "homeLabel": "Home",
        "resourcesLabel": "Resources",
        "sections": [
          {
            "id": "recent",
            "label": "Recent",
            "items": [
              {
                "id": "c/club1",
                "label": "c/club1"
              },
              {
                "id": "c/pirate-radio",
                "label": "c/pirate-radio"
              }
            ]
          },
          {
            "id": "communities",
            "label": "Communities",
            "items": [
              {
                "id": "c/builders",
                "label": "c/builders"
              },
              {
                "id": "c/mixes",
                "label": "c/mixes"
              },
              {
                "id": "c/samples",
                "label": "c/samples"
              }
            ]
          }
        ],
        "resourceItems": [
          {
            "id": "blog",
            "label": "Blog"
          },
          {
            "id": "terms-of-service",
            "label": "Terms of Service"
          },
          {
            "id": "privacy-policy",
            "label": "Privacy Policy"
          }
        ],
        "yourCommunitiesLabel": "Your Communities"
      },
      "mobileFooter": {
        "connectLabel": "Connect",
        "createLabel": "Create",
        "homeLabel": "Home",
        "inboxAriaLabel": "Inbox",
        "inboxLabel": "Inbox",
        "primaryNavAriaLabel": "Primary",
        "profileAriaLabel": "Profile",
        "profileLabel": "Profile"
      },
      "storybook": {
        "contentAreaLabel": "Content area",
        "desktopHeaderBody": "Header is standalone. Compose it into the real app shell, not into onboarding cards.",
        "mobileHeaderBody": "Mobile header only.",
        "mobileFooterBody": "Mobile footer only.",
        "mobileChromeLead": "Standalone shell chrome preview.",
        "mobileChromeFollow": "Header and footer stay reusable and separate from onboarding.",
        "standaloneDesktopSearchPlaceholder": "Find anything"
      }
    }
  },
  "ar": {
    "routes": {
      "common": {
        "backHome": "العودة إلى الرئيسية",
        "bestTab": "الأفضل",
        "commentsHeading": "التعليقات",
        "createAction": "أنشئ",
        "joinedStatLabel": "انضم",
        "newTab": "الجديد",
        "topAll": "كل الوقت",
        "topDay": "اليوم",
        "topHour": "هذه الساعة",
        "topMonth": "هذا الشهر",
        "topTab": "الأعلى",
        "topWeek": "هذا الأسبوع",
        "topYear": "هذا العام"
      },
      "home": {
        "membersLabel": "{count} عضو",
        "railTitle": "المنشورات الحديثة",
        "subtitle": "",
        "title": "الرئيسية"
      },
      "yourCommunities": {
        "gatedLabel": "مغلق",
        "openLabel": "مفتوح",
        "railTitle": "مساحاتك",
        "subtitle": "خلاصة مخصّصة للأعضاء. أبقِها مركّزة على الهاتف ودع الشريط الجانبي يتحمّل التنقل الأثقل.",
        "title": "مجتمعاتك"
      },
      "post": {
        "commentsBody": "الردود لا يتم تحميلها في نسخة الويب هذه بعد.",
        "description": "عرض حي للمنشور لسجلات `GET /posts/{post_id}`.",
        "fallbackTitle": "منشور"
      },
      "onboarding": {
        "chooseNameAction": "اسم المستخدم",
        "description": "مسار إعداد من ثلاث خطوات للتحقق من Reddit واختيار الاسم واقتراح المجتمعات.",
        "importKarmaAction": "Reddit",
        "suggestedCommunitiesAction": "المجتمعات",
        "title": "أكمل إعداد هوية Pirate الخاصة بك"
      },
      "auth": {
        "body": "سجّل الدخول لإنشاء أو استئناف جلسة Pirate في المتصفح. بعد الاتصال ستعرض هذه الصفحة حالة الحساب والإعداد الحالية.",
        "description": "نقطة دخول الحساب لتسجيل الدخول من المتصفح، وحالة الجلسة، ومسارات التحقق.",
        "title": "الحساب"
      },
      "authDevice": {
        "description": "مسار تسليم المتصفح لتسجيل الدخول من الطرفية أو الجهاز. تسجل الصفحة الدخول عبر Privy، وتفحص حالة الإعداد، ثم تفوض جلسة الجهاز المنتظرة.",
        "title": "مصادقة الجهاز"
      },
      "inbox": {
        "body": "استخدم هذه الصفحة لفحص جلسة المتصفح الحالية، وحالة التحقق، وجاهزية الإعداد.",
        "description": "سطح حالة خاص بالحساب للتحقق، والإعداد، وأحداث النظام.",
        "title": "الوارد"
      },
      "createCommunity": {
        "description": "تدفق إنشاء مجتمع معتمد على النطاق مع تحقق حي من الحساب وربط فعلي للإرسال.",
        "title": "أنشئ مجتمعًا"
      },
      "notFound": {
        "body": "يغطي هيكل الويب الحالي الرئيسية، والخلاصات، والمجتمعات، والمنشورات، والملفات الشخصية، والإعداد، والحساب، والوارد، وإنشاء المجتمع.",
        "description": "لا توجد صفحة مجهزة للمسار {path}.",
        "title": "المسار غير موجود"
      }
    },
    "shell": {
      "appHeader": {
        "connectLabel": "اتصل",
        "createLabel": "أنشئ",
        "homeAriaLabel": "اذهب إلى الصفحة الرئيسية",
        "notificationsAriaLabel": "الإشعارات",
        "openNavigationAriaLabel": "افتح التنقل",
        "profileAriaLabel": "افتح الملف الشخصي",
        "searchAriaLabel": "ابحث في بايرت",
        "searchPlaceholder": "ابحث في Pirate",
        "searchUnavailableToast": "البحث غير متاح بعد.",
        "verifyLabel": "تحقّق"
      },
      "appSidebar": {
        "brandLabel": "Pirate",
        "createCommunityLabel": "أنشئ مجتمعًا",
        "homeAriaLabel": "اذهب إلى الصفحة الرئيسية",
        "homeLabel": "الرئيسية",
        "resourcesLabel": "الموارد",
        "sections": [
          {
            "id": "recent",
            "label": "الأخيرة",
            "items": [
              {
                "id": "c/club1",
                "label": "c/النادي-١"
              },
              {
                "id": "c/pirate-radio",
                "label": "c/راديو-بايرت"
              }
            ]
          },
          {
            "id": "communities",
            "label": "المجتمعات",
            "items": [
              {
                "id": "c/builders",
                "label": "c/البناؤون"
              },
              {
                "id": "c/mixes",
                "label": "c/الميكسات"
              },
              {
                "id": "c/samples",
                "label": "c/السامبلز"
              }
            ]
          }
        ],
        "resourceItems": [
          {
            "id": "blog",
            "label": "المدونة"
          },
          {
            "id": "terms-of-service",
            "label": "شروط الخدمة"
          },
          {
            "id": "privacy-policy",
            "label": "سياسة الخصوصية"
          }
        ],
        "yourCommunitiesLabel": "مجتمعاتك"
      },
      "mobileFooter": {
        "connectLabel": "اتصل",
        "createLabel": "أنشئ",
        "homeLabel": "الرئيسية",
        "inboxAriaLabel": "الوارد",
        "inboxLabel": "الوارد",
        "primaryNavAriaLabel": "التنقل الرئيسي",
        "profileAriaLabel": "الملف الشخصي",
        "profileLabel": "الملف الشخصي"
      },
      "storybook": {
        "contentAreaLabel": "منطقة المحتوى",
        "desktopHeaderBody": "الهيدر مستقل. كوّنه داخل غلاف التطبيق الحقيقي، وليس داخل بطاقات الإعداد.",
        "mobileHeaderBody": "الهيدر المحمول فقط.",
        "mobileFooterBody": "التذييل المحمول فقط.",
        "mobileChromeLead": "معاينة مستقلة لكروم التطبيق.",
        "mobileChromeFollow": "يبقى الهيدر والتذييل قابلين لإعادة الاستخدام ومنفصلين عن بطاقات الإعداد.",
        "standaloneDesktopSearchPlaceholder": "ابحث عن أي شيء"
      }
    }
  }
} as const;

export type RealLocaleCode = (typeof REAL_LOCALE_CODES)[number];
export type LocaleNamespace = (typeof LOCALE_NAMESPACES)[number];
export type GeneratedLocaleCatalogs = typeof GENERATED_LOCALE_CATALOGS;
