// This file is generated by `bun run locales:generate`. Do not edit manually.

export const REAL_LOCALE_CODES = ["en","ar","zh"] as const;
export const LOCALE_NAMESPACES = ["routes","shell"] as const;

export const GENERATED_LOCALE_CATALOGS = {
  "en": {
    "routes": {
      "common": {
        "backHome": "Back Home",
        "bestTab": "Best",
        "chooseCommunity": "Choose a community",
        "commentsHeading": "Comments",
        "createAction": "Create",
        "cancelReply": "Cancel",
        "joinedStatLabel": "Joined",
        "loadMoreReplies": "Load more replies",
        "loadReplies": "Load replies",
        "loadingReplies": "Loading replies...",
        "newTab": "New",
        "noComments": "No comments yet.",
        "noRecentCommunities": "No recent communities.",
        "replyAction": "Reply",
        "replyPlaceholder": "Write a reply",
        "showOriginal": "Show original",
        "showTranslation": "Show translation",
        "submitReply": "Post reply",
        "topAll": "All time",
        "topDay": "Today",
        "topHour": "This hour",
        "topMonth": "This month",
        "topTab": "Top",
        "topWeek": "This week",
        "topYear": "This year"
      },
      "home": {
        "createCommunityLabel": "Create community",
        "emptyHomeBody": "Join a community or create one to start building your home feed.",
        "emptyHomeTitle": "No posts yet",
        "emptyYourCommunitiesBody": "Communities you create or join show up here.",
        "emptyYourCommunitiesTitle": "No communities yet",
        "membersLabel": "{count} members",
        "railTitle": "Recent posts",
        "subtitle": "",
        "title": "Home"
      },
      "yourCommunities": {
        "gatedLabel": "Gated",
        "openLabel": "Open",
        "railTitle": "Your Spaces",
        "subtitle": "A member-scoped feed shell. Keep it tight on mobile and let the sidebar carry the heavier navigation.",
        "title": "Your Communities"
      },
      "post": {
        "commentsBody": "Thread replies are not scaffolded yet. This route exists to pin the URL contract and page chrome for `post_id` reads.",
        "description": "Single-thread route shell for the future `GET /posts/{post_id}` read.",
        "fallbackTitle": "Post"
      },
      "community": {
        "aboutTab": "About",
        "createPostLabel": "Create Post",
        "feedTab": "Feed",
        "membersLabel": "Members",
        "modToolsLabel": "Mod Tools",
        "requirementsLabel": "Requirements",
        "rulesLabel": "Rules",
        "title": "Community"
      },
      "interactionGate": {
        "blockedReplyDescription": "This community's requirements block you from replying right now.",
        "blockedVoteDescription": "This community's requirements block you from voting right now.",
        "cantReplyHereTitle": "You can't reply here",
        "cantVoteHereTitle": "You can't vote here",
        "close": "Close",
        "connectToContinue": "Connect to continue.",
        "couldNotCheckRequirements": "Couldn't check this community's interaction requirements.",
        "joinInCommunity": "{joinLabel} in {communityName}",
        "joinToReplyDescription": "{joinLabel} in {communityName} before you reply.",
        "joinToReplyTitle": "{joinLabel} to reply",
        "joinToVoteDescription": "{joinLabel} in {communityName} before you vote.",
        "joinToVoteTitle": "{joinLabel} to vote",
        "openCommunity": "Open {communityName}",
        "readyDescription": "You can interact here.",
        "readyTitle": "Ready",
        "verifyInCommunity": "Verify in {communityName}",
        "verifyToReplyDescription": "Complete ID check to reply here.",
        "verifyToReplyTitle": "Verify to reply",
        "verifyToVoteDescription": "Complete ID check to vote here.",
        "verifyToVoteTitle": "Verify to vote",
        "bannedDescription": "You are not eligible to join this community."
      },
      "createPost": {
        "access": {
          "paidDescription": "Preview in feed. Full track unlocks after purchase.",
          "paidUnlock": "Paid unlock",
          "public": "Public",
          "publicDescription": "Anyone can play the full track.",
          "rightsAttested": "I have the rights to publish and monetize this track.",
          "useRegionalPricing": "Use community regional pricing"
        },
        "actions": {
          "post": "Post",
          "publishRemix": "Publish remix"
        },
        "audience": {
          "private": "Private",
          "privateDescription": "Joined members can read this post.",
          "public": "Public",
          "publicDisabledReason": "This community already limits who can read posts.",
          "publicDescription": "Anyone can read this post."
        },
        "backToCommunity": "Back to community",
        "buttons": {
          "chooseFile": "Choose file",
          "clear": "Clear",
          "replace": "Replace"
        },
        "derivative": {
          "searchSourceTracks": "Search source tracks"
        },
        "empty": {
          "noOptionalQualifiers": "No optional qualifiers are available for this community.",
          "noQualifiers": "No qualifiers found.",
          "noReferences": "No upstream works attached yet.",
          "noSongs": "No songs found.",
          "noSourceTracks": "No source tracks found."
        },
        "fields": {
          "audio": "Audio",
          "body": "Body",
          "canvasVideo": "Canvas video",
          "caption": "Caption",
          "commentary": "Commentary",
          "coverArt": "Cover art",
          "genre": "Genre",
          "image": "Image",
          "instrumentalStem": "Instrumental stem",
          "lyrics": "Lyrics",
          "primaryLanguage": "Primary language",
          "secondaryLanguage": "Secondary language",
          "song": "Song",
          "title": "Title",
          "unlockPriceUsd": "Unlock price (USD)",
          "url": "URL",
          "video": "Video",
          "vocalStem": "Vocal stem",
          "previewClip": "Preview clip"
        },
        "identity": {
          "addQualifiers": "Add qualifiers",
          "postAnonymously": "Post anonymously",
          "qualifiersHelp": "Attach verified qualifiers to this post. Qualifiers already implied by community gates are omitted.",
          "searchQualifiers": "Search qualifiers"
        },
        "labels": {
          "source": "Source"
        },
        "membershipRequiredDescription": "Only community members can publish posts here.",
        "membershipRequiredTitle": "Join this community before posting",
        "none": "None",
        "placeholders": {
          "artist": "Artist",
          "body": "Write your post",
          "caption": "Add a caption",
          "commentary": "Add commentary",
          "lyrics": "Paste lyrics",
          "optional": "Optional",
          "selectGenre": "Select genre",
          "selectLanguage": "Select language",
          "songSearch": "Search Pirate songbase",
          "songTitle": "Song title",
          "sourceTrackSearch": "Search Pirate / Story assets",
          "title": "Title",
          "unlockPrice": "1.00",
          "url": "https://"
        },
        "sections": {
          "access": "Access",
          "audience": "Audience",
          "postAs": "Post as",
          "qualifiers": "Qualifiers",
          "sourceTrack": "Source track"
        },
        "setlist": {
          "cannotFindTrack": "Can't find the track?",
          "hideManualDetails": "Hide manual details",
          "searchSongs": "Search songs for setlist item"
        },
        "songModes": {
          "original": "Original",
          "remix": "Remix"
        },
        "tabs": {
          "image": "Image",
          "link": "Link",
          "live": "Live",
          "song": "Song",
          "text": "Text",
          "video": "Video"
        },
        "title": "Create post",
        "upload": {
          "artworkHelp": "Shows in feed, release, and player surfaces.",
          "cover": "Cover",
          "noFileSelected": "No file selected",
          "squareArtwork": "Upload square artwork"
        }
      },
      "onboarding": {
        "actions": {
          "generateHandle": "Generate a new handle",
          "checkAgain": "Check again",
          "continue": "Continue",
          "getCode": "Get code",
          "next": "Next",
          "skip": "Skip"
        },
        "chooseNameAction": "Choose Name",
        "description": "Single onboarding route with client-managed phases. No nested onboarding URLs are locked yet.",
        "errors": {
          "chooseHandle": "Choose a handle before continuing",
          "renameFailed": "Handle rename failed"
        },
        "fields": {
          "handle": "Handle",
          "redditCode": "Reddit {surface} code",
          "redditUsername": "Reddit username"
        },
        "importKarmaAction": "Import Karma",
        "notes": {
          "addCodeToProfile": "Add this code to your Reddit profile Description:",
          "checkedRedditAt": "Checked Reddit at {time}. The code is not visible yet. Save your profile, wait a few seconds, then click Check again.",
          "checkingRedditNow": "Checking Reddit now...",
          "handleAvailable": "{handle}.pirate is available",
          "handleTaken": "{handle}.pirate is taken",
          "importing": "Importing...",
          "noSuggestionsYet": "No community suggestions yet. Join some from your feed later.",
          "saveProfileThenCheckAgain": "After saving your Reddit profile Description, wait a few seconds and click Check again.",
          "startingImport": "Starting import..."
        },
        "placeholders": {
          "handle": "Choose your handle"
        },
        "progressLabel": "Onboarding",
        "stepCount": "{current}/{total}",
        "suggestedCommunitiesAction": "Suggested Communities",
        "surfaces": {
          "about": "about",
          "bio": "bio",
          "profile": "profile"
        },
        "title": "Finish setting up your Pirate identity"
      },
      "inbox": {
        "body": "Keep `/inbox` as a neutral placeholder until notifications or messaging are specified as real product surfaces.",
        "description": "This route is scaffolded so the mobile nav can point somewhere truthful while inbox behavior is still undefined.",
        "emptyState": "No notifications yet",
        "loading": "Loading...",
        "recentActivity": "Recent activity",
        "someone": "Someone",
        "taskActionNeeded": "Action needed",
        "taskDismiss": "Dismiss",
        "taskNamespaceVerificationRequired": "Verify your community namespace",
        "taskVerify": "Verify",
        "title": "Inbox"
      },
      "createCommunity": {
        "reopenVerification": "Reopen verification",
        "description": "Scaffolded shell around the existing community composer composition. Submission is not wired yet.",
        "startVerification": "Verify",
        "title": "Create a community",
        "verifyDescription": "Verify before creating a community.",
        "verifyPendingDescription": "Complete your palm scan to continue.",
        "verifyPendingTitle": "Finish verification",
        "verifyStartDescription": "Scan your palm to prove you're human. No photos or data is saved.",
        "verifyStartTitle": "Verify"
      },
      "profile": {
        "commentsTab": "Comments",
        "editProfile": "Edit profile",
        "emptyActivity": "No activity yet.",
        "emptyPosts": "No posts yet.",
        "emptyScrobbles": "No scrobbles yet.",
        "follow": "Follow",
        "followersLabel": "Followers",
        "following": "Following",
        "followingLabel": "Following",
        "handleUpdated": "Handle updated",
        "message": "Message",
        "moreActions": "More actions",
        "overviewTab": "Overview",
        "postsTab": "Posts",
        "scrobblesTab": "Scrobbles",
        "shareProfile": "Share profile",
        "title": "Profile",
        "verificationTitle": "Verification",
        "walletTitle": "Wallet"
      },
      "publicProfile": {
        "aboutTab": "About",
        "communitiesTitle": "Communities",
        "emptyAbout": "No info yet.",
        "emptyPosts": "No posts yet.",
        "emptyScrobbles": "No scrobbles yet.",
        "emptySongs": "No songs yet.",
        "emptyVideos": "No videos yet.",
        "errorDescription": "This public profile could not be loaded right now.",
        "errorTitle": "Public profile",
        "joinedLabel": "Joined",
        "notFoundDescription": "We could not find a public profile for {path}.",
        "notFoundTitle": "Profile not found",
        "openInPirate": "Open in Pirate",
        "postsTab": "Posts",
        "scrobblesTab": "Scrobbles",
        "songsTab": "Songs",
        "videosTab": "Videos"
      },
      "publicCommunity": {
        "emptyPosts": "No posts yet",
        "errorDescription": "This community could not be loaded right now.",
        "errorTitle": "Community",
        "notFoundDescription": "We could not find c/{communityId}.",
        "notFoundTitle": "Community not found"
      },
      "settings": {
        "ageStatusLabel": "Age status",
        "ageVerified": "18+ verified",
        "appearanceSection": "Appearance",
        "appLanguageLabel": "App language",
        "bioLabel": "Bio",
        "connectedWalletsSection": "Connected wallets",
        "coverTitle": "Cover",
        "displayNameLabel": "Display name",
        "displayNameRequired": "Display name is required.",
        "handleNoteEns": "ENS",
        "handleNoteEnsRefresh": "ENS needs refresh",
        "handleNoteEnsUnverified": "ENS not verified",
        "handleNotePirate": "Pirate handle",
        "identitySection": "Identity",
        "languageSection": "Language",
        "linkedHandlesSection": "Linked handles",
        "localeArabic": "Arabic",
        "localeEnglish": "English",
        "localeMandarin": "Mandarin",
        "localePseudo": "Pseudo",
        "noConnectedWallets": "No connected wallets yet.",
        "notVerified": "Not verified",
        "noWalletConnected": "No wallet connected",
        "postsAndCommentsLabel": "Posts and comments",
        "postsAndCommentsNote": "Primary public byline",
        "preferencesTab": "Preferences",
        "primaryHandleLabel": "Primary",
        "primaryWalletLabel": "Primary wallet",
        "primaryWalletNote": "Primary wallet",
        "profileSection": "Profile",
        "profileUpdated": "Profile updated",
        "profileTab": "Profile",
        "removeAvatar": "Remove avatar",
        "removeCover": "Remove cover",
        "replaceAvatar": "Replace avatar",
        "replaceCover": "Replace cover",
        "savePreferences": "Save preferences",
        "saveProfile": "Save profile",
        "sectionsLabel": "Settings sections",
        "selectLanguage": "Select language",
        "title": "Settings",
        "uploadAvatar": "Upload avatar",
        "uploadCover": "Upload cover",
        "avatarTitle": "Avatar",
        "preferencesUpdated": "Preferences updated",
        "walletTab": "Wallet"
      },
      "notFound": {
        "body": "The first scaffold only locks a small set of routes: home, feeds, communities, posts, profiles, onboarding, inbox placeholder, and community create.",
        "description": "No scaffolded page exists for {path}.",
        "title": "Route not found"
      }
    },
    "shell": {
      "appHeader": {
        "connectLabel": "Connect",
        "createEmptyLabel": "No recent communities.",
        "createLabel": "Create",
        "createPickerTitle": "Create post in",
        "homeAriaLabel": "Go to home",
        "notificationsAriaLabel": "Notifications",
        "openNavigationAriaLabel": "Open navigation",
        "profileAriaLabel": "Open profile",
        "searchAriaLabel": "Search Pirate",
        "searchPlaceholder": "Search Pirate",
        "searchUnavailableToast": "Search is not scaffolded yet."
      },
      "appSidebar": {
        "brandLabel": "Pirate",
        "createCommunityLabel": "Create Community",
        "homeAriaLabel": "Go to home",
        "homeLabel": "Home",
        "resourcesLabel": "Resources",
        "sections": [
          {
            "id": "recent",
            "label": "Recent",
            "items": [
              {
                "id": "c/club1",
                "label": "c/club1"
              },
              {
                "id": "c/pirate-radio",
                "label": "c/pirate-radio"
              }
            ]
          },
          {
            "id": "communities",
            "label": "Communities",
            "items": [
              {
                "id": "c/builders",
                "label": "c/builders"
              },
              {
                "id": "c/mixes",
                "label": "c/mixes"
              },
              {
                "id": "c/samples",
                "label": "c/samples"
              }
            ]
          },
          {
            "id": "moderation",
            "label": "Moderation",
            "items": [
              {
                "id": "c/pirate",
                "label": "c/pirate"
              },
              {
                "id": "c/builders",
                "label": "c/builders"
              }
            ]
          }
        ],
        "resourceItems": [
          {
            "id": "blog",
            "label": "Blog"
          },
          {
            "id": "terms-of-service",
            "label": "Terms of Service"
          },
          {
            "id": "privacy-policy",
            "label": "Privacy Policy"
          }
        ],
        "yourCommunitiesLabel": "Your Communities"
      },
      "mobileFooter": {
        "createLabel": "Create",
        "homeLabel": "Home",
        "inboxAriaLabel": "Inbox",
        "inboxLabel": "Inbox",
        "primaryNavAriaLabel": "Primary",
        "profileAriaLabel": "Profile",
        "profileLabel": "Profile"
      },
      "storybook": {
        "contentAreaLabel": "Content area",
        "desktopHeaderBody": "Header is standalone. Compose it into the real app shell, not into onboarding cards.",
        "mobileHeaderBody": "Mobile header only.",
        "mobileFooterBody": "Mobile footer only.",
        "mobileChromeLead": "Standalone shell chrome preview.",
        "mobileChromeFollow": "Header and footer stay reusable and separate from onboarding.",
        "standaloneDesktopSearchPlaceholder": "Find anything"
      }
    }
  },
  "ar": {
    "routes": {
      "common": {
        "backHome": "العودة إلى الرئيسية",
        "bestTab": "الأفضل",
        "chooseCommunity": "اختر مجتمعًا",
        "commentsHeading": "التعليقات",
        "createAction": "أنشئ",
        "cancelReply": "إلغاء",
        "joinedStatLabel": "انضم",
        "loadMoreReplies": "حمّل المزيد من الردود",
        "loadReplies": "حمّل الردود",
        "loadingReplies": "جارٍ تحميل الردود...",
        "newTab": "الجديد",
        "noComments": "لا توجد تعليقات بعد.",
        "noRecentCommunities": "لا توجد مجتمعات حديثة.",
        "replyAction": "رد",
        "replyPlaceholder": "اكتب ردًا",
        "showOriginal": "أظهر الأصل",
        "showTranslation": "أظهر الترجمة",
        "submitReply": "انشر الرد",
        "topAll": "كل الوقت",
        "topDay": "اليوم",
        "topHour": "هذه الساعة",
        "topMonth": "هذا الشهر",
        "topTab": "الأعلى",
        "topWeek": "هذا الأسبوع",
        "topYear": "هذا العام"
      },
      "home": {
        "createCommunityLabel": "أنشئ مجتمعًا",
        "emptyHomeBody": "انضم إلى مجتمع أو أنشئ واحدًا لتبدأ في بناء خلاصتك الرئيسية.",
        "emptyHomeTitle": "لا توجد منشورات بعد",
        "emptyYourCommunitiesBody": "المجتمعات التي تنشئها أو تنضم إليها تظهر هنا.",
        "emptyYourCommunitiesTitle": "لا توجد مجتمعات بعد",
        "membersLabel": "{count} عضو",
        "railTitle": "المنشورات الحديثة",
        "subtitle": "",
        "title": "الرئيسية"
      },
      "yourCommunities": {
        "gatedLabel": "مغلق",
        "openLabel": "مفتوح",
        "railTitle": "مساحاتك",
        "subtitle": "خلاصة مخصّصة للأعضاء. أبقِها مركّزة على الهاتف ودع الشريط الجانبي يتحمّل التنقل الأثقل.",
        "title": "مجتمعاتك"
      },
      "post": {
        "commentsBody": "ردود السلسلة غير مهيأة بعد. هذا المسار موجود لتثبيت عقد عنوان URL وهيكل الصفحة لقراءات `post_id`.",
        "description": "هيكل مسار لسلسلة مفردة لقراءة `GET /posts/{post_id}` مستقبلًا.",
        "fallbackTitle": "منشور"
      },
      "community": {
        "aboutTab": "حول",
        "createPostLabel": "أنشئ منشورًا",
        "feedTab": "الخلاصة",
        "membersLabel": "الأعضاء",
        "modToolsLabel": "أدوات الإشراف",
        "requirementsLabel": "المتطلبات",
        "rulesLabel": "القواعد",
        "title": "المجتمع"
      },
      "interactionGate": {
        "blockedReplyDescription": "متطلبات هذا المجتمع تمنعك من الرد الآن.",
        "blockedVoteDescription": "متطلبات هذا المجتمع تمنعك من التصويت الآن.",
        "cantReplyHereTitle": "لا يمكنك الرد هنا",
        "cantVoteHereTitle": "لا يمكنك التصويت هنا",
        "close": "إغلاق",
        "connectToContinue": "اتصل للمتابعة.",
        "couldNotCheckRequirements": "تعذر التحقق من متطلبات التفاعل في هذا المجتمع.",
        "joinInCommunity": "{joinLabel} في {communityName}",
        "joinToReplyDescription": "{joinLabel} في {communityName} قبل أن ترد.",
        "joinToReplyTitle": "{joinLabel} قبل الرد",
        "joinToVoteDescription": "{joinLabel} في {communityName} قبل أن تصوّت.",
        "joinToVoteTitle": "{joinLabel} قبل التصويت",
        "openCommunity": "افتح {communityName}",
        "readyDescription": "يمكنك التفاعل هنا.",
        "readyTitle": "جاهز",
        "verifyInCommunity": "تحقق في {communityName}",
        "verifyToReplyDescription": "أكمل فحص الهوية للرد هنا.",
        "verifyToReplyTitle": "تحقق قبل الرد",
        "verifyToVoteDescription": "أكمل فحص الهوية للتصويت هنا.",
        "verifyToVoteTitle": "تحقق قبل التصويت",
        "bannedDescription": "أنت غير مؤهل للانضمام إلى هذا المجتمع."
      },
      "createPost": {
        "access": {
          "paidDescription": "تظهر معاينة في الخلاصة، ويُفتح المسار الكامل بعد الشراء.",
          "paidUnlock": "فتح مدفوع",
          "public": "عام",
          "publicDescription": "يمكن لأي شخص تشغيل المسار الكامل.",
          "rightsAttested": "أؤكد أن لدي الحقوق لنشر هذا المسار وتحقيق الدخل منه.",
          "useRegionalPricing": "استخدم التسعير الإقليمي للمجتمع"
        },
        "actions": {
          "post": "انشر",
          "publishRemix": "انشر الريمكس"
        },
        "audience": {
          "private": "للأعضاء فقط",
          "privateDescription": "يمكن للأعضاء المنضمين فقط قراءة هذا المنشور.",
          "public": "عام",
          "publicDisabledReason": "هذا المجتمع يقيّد بالفعل من يمكنه قراءة المنشورات.",
          "publicDescription": "يمكن لأي شخص قراءة هذا المنشور."
        },
        "backToCommunity": "العودة إلى المجتمع",
        "buttons": {
          "chooseFile": "اختر ملفًا",
          "clear": "امسح",
          "replace": "استبدل"
        },
        "derivative": {
          "searchSourceTracks": "ابحث عن المسارات المصدر"
        },
        "empty": {
          "noOptionalQualifiers": "لا توجد مؤهلات اختيارية متاحة لهذا المجتمع.",
          "noQualifiers": "لم يتم العثور على مؤهلات.",
          "noReferences": "لا توجد أعمال مصدر مرفقة بعد.",
          "noSongs": "لم يتم العثور على أغانٍ.",
          "noSourceTracks": "لم يتم العثور على مسارات مصدر."
        },
        "fields": {
          "audio": "الصوت",
          "body": "المحتوى",
          "canvasVideo": "فيديو الغلاف المتحرك",
          "caption": "التعليق",
          "commentary": "التعليق",
          "coverArt": "صورة الغلاف",
          "genre": "النوع",
          "image": "الصورة",
          "instrumentalStem": "مسار الآلات",
          "lyrics": "الكلمات",
          "primaryLanguage": "اللغة الأساسية",
          "secondaryLanguage": "اللغة الثانوية",
          "song": "الأغنية",
          "title": "العنوان",
          "unlockPriceUsd": "سعر الفتح (دولار)",
          "url": "الرابط",
          "video": "الفيديو",
          "vocalStem": "المسار الصوتي",
          "previewClip": "مقطع المعاينة"
        },
        "identity": {
          "addQualifiers": "أضف مؤهلات",
          "postAnonymously": "انشر بشكل مجهول",
          "qualifiersHelp": "أرفق مؤهلات موثقة بهذا المنشور. المؤهلات التي يفرضها المجتمع مسبقًا لا تظهر هنا.",
          "searchQualifiers": "ابحث عن المؤهلات"
        },
        "labels": {
          "source": "المصدر"
        },
        "membershipRequiredDescription": "يمكن لأعضاء المجتمع فقط نشر المنشورات هنا.",
        "membershipRequiredTitle": "انضم إلى هذا المجتمع قبل النشر",
        "none": "لا شيء",
        "placeholders": {
          "artist": "الفنان",
          "body": "اكتب منشورك",
          "caption": "أضف تعليقًا",
          "commentary": "أضف تعليقًا",
          "lyrics": "ألصق الكلمات",
          "optional": "اختياري",
          "selectGenre": "اختر النوع",
          "selectLanguage": "اختر اللغة",
          "songSearch": "ابحث في مكتبة Pirate الموسيقية",
          "songTitle": "عنوان الأغنية",
          "sourceTrackSearch": "ابحث في أصول Pirate / Story",
          "title": "العنوان",
          "unlockPrice": "1.00",
          "url": "https://"
        },
        "sections": {
          "access": "الوصول",
          "audience": "الجمهور",
          "postAs": "انشر باسم",
          "qualifiers": "المؤهلات",
          "sourceTrack": "المسار المصدر"
        },
        "setlist": {
          "cannotFindTrack": "ألا تجد المسار؟",
          "hideManualDetails": "أخفِ التفاصيل اليدوية",
          "searchSongs": "ابحث عن أغانٍ لعنصر قائمة التشغيل"
        },
        "songModes": {
          "original": "أصلي",
          "remix": "ريمكس"
        },
        "tabs": {
          "image": "صورة",
          "link": "رابط",
          "live": "بث مباشر",
          "song": "أغنية",
          "text": "نص",
          "video": "فيديو"
        },
        "title": "أنشئ منشورًا",
        "upload": {
          "artworkHelp": "تظهر في الخلاصة وصفحة الإصدار وواجهة المشغل.",
          "cover": "الغلاف",
          "noFileSelected": "لم يتم اختيار ملف",
          "squareArtwork": "ارفع غلافًا مربعًا"
        }
      },
      "onboarding": {
        "actions": {
          "generateHandle": "أنشئ اسمًا جديدًا",
          "checkAgain": "تحقق مرة أخرى",
          "continue": "تابع",
          "getCode": "احصل على الرمز",
          "next": "التالي",
          "skip": "تخطَّ"
        },
        "chooseNameAction": "اختر الاسم",
        "description": "مسار إعداد واحد بمراحل تُدار من العميل. لم يتم تثبيت عناوين URL المتداخلة للإعداد بعد.",
        "errors": {
          "chooseHandle": "اختر اسمًا قبل المتابعة",
          "renameFailed": "فشل تغيير الاسم"
        },
        "fields": {
          "handle": "الاسم",
          "redditCode": "رمز ريديت {surface}",
          "redditUsername": "اسم مستخدم Reddit"
        },
        "importKarmaAction": "استورد الكارما",
        "notes": {
          "addCodeToProfile": "أضف هذا الرمز إلى وصف ملفك الشخصي على Reddit:",
          "checkedRedditAt": "تم فحص Reddit عند {time}. الرمز غير ظاهر بعد. احفظ ملفك الشخصي، وانتظر بضع ثوانٍ، ثم اضغط على \"تحقق مرة أخرى\".",
          "checkingRedditNow": "جارٍ فحص Reddit الآن...",
          "handleAvailable": "الاسم {handle}.pirate متاح",
          "handleTaken": "الاسم {handle}.pirate مستخدم",
          "importing": "جارٍ الاستيراد...",
          "noSuggestionsYet": "لا توجد مجتمعات مقترحة بعد. يمكنك الانضمام من خلاصتك لاحقًا.",
          "saveProfileThenCheckAgain": "بعد حفظ وصف ملفك الشخصي على Reddit، انتظر بضع ثوانٍ ثم اضغط على \"تحقق مرة أخرى\".",
          "startingImport": "بدء الاستيراد..."
        },
        "placeholders": {
          "handle": "اختر اسمك"
        },
        "progressLabel": "الإعداد",
        "stepCount": "{current}/{total}",
        "suggestedCommunitiesAction": "مجتمعات مقترحة",
        "surfaces": {
          "about": "حول",
          "bio": "النبذة",
          "profile": "الملف الشخصي"
        },
        "title": "أكمل إعداد هويتك على بايرت"
      },
      "inbox": {
        "body": "أبقِ `/inbox` كعنصر نائب محايد حتى يتم تحديد الإشعارات أو المراسلة كسطوح منتج حقيقية.",
        "description": "تم تجهيز هذا المسار حتى يشير إليه تنقل الهاتف بصدق بينما لا يزال سلوك الوارد غير محدد.",
        "emptyState": "لا توجد إشعارات بعد",
        "loading": "جارٍ التحميل...",
        "recentActivity": "النشاط الأخير",
        "someone": "شخص ما",
        "taskActionNeeded": "إجراء مطلوب",
        "taskDismiss": "إخفاء",
        "taskNamespaceVerificationRequired": "تحقق من مساحة اسم مجتمعك",
        "taskVerify": "تحقق",
        "title": "الوارد"
      },
      "createCommunity": {
        "reopenVerification": "أعد فتح التحقق",
        "description": "هيكل جاهز حول مكوّن إنشاء المجتمع الحالي. الإرسال غير موصول بعد.",
        "startVerification": "تحقق",
        "title": "أنشئ مجتمعًا",
        "verifyDescription": "تحقق قبل إنشاء مجتمع.",
        "verifyPendingDescription": "أكمل مسح راحة اليد للمتابعة.",
        "verifyPendingTitle": "أكمل التحقق",
        "verifyStartDescription": "امسح راحة يدك لإثبات أنك إنسان. لا يتم حفظ أي صور أو بيانات.",
        "verifyStartTitle": "تحقق"
      },
      "profile": {
        "commentsTab": "التعليقات",
        "editProfile": "عدّل الملف الشخصي",
        "emptyActivity": "لا يوجد نشاط بعد.",
        "emptyPosts": "لا توجد منشورات بعد.",
        "emptyScrobbles": "لا توجد سكروبلات بعد.",
        "follow": "تابع",
        "followersLabel": "المتابعون",
        "following": "تتابع",
        "followingLabel": "يتابع",
        "handleUpdated": "تم تحديث المعرّف",
        "message": "راسل",
        "moreActions": "مزيد من الإجراءات",
        "overviewTab": "نظرة عامة",
        "postsTab": "المنشورات",
        "scrobblesTab": "السكروبلات",
        "shareProfile": "شارك الملف الشخصي",
        "title": "الملف الشخصي",
        "verificationTitle": "التحقق",
        "walletTitle": "المحفظة"
      },
      "publicProfile": {
        "aboutTab": "حول",
        "communitiesTitle": "المجتمعات",
        "emptyAbout": "لا توجد معلومات بعد.",
        "emptyPosts": "لا توجد منشورات بعد.",
        "emptyScrobbles": "لا توجد سكروبلات بعد.",
        "emptySongs": "لا توجد أغانٍ بعد.",
        "emptyVideos": "لا توجد فيديوهات بعد.",
        "errorDescription": "تعذر تحميل هذا الملف الشخصي العام الآن.",
        "errorTitle": "الملف الشخصي العام",
        "joinedLabel": "انضم",
        "notFoundDescription": "لم نتمكن من العثور على ملف شخصي عام لـ {path}.",
        "notFoundTitle": "الملف الشخصي غير موجود",
        "openInPirate": "افتح في بايرت",
        "postsTab": "المنشورات",
        "scrobblesTab": "السكروبلات",
        "songsTab": "الأغاني",
        "videosTab": "الفيديوهات"
      },
      "publicCommunity": {
        "emptyPosts": "لا توجد منشورات بعد",
        "errorDescription": "تعذر تحميل هذا المجتمع الآن.",
        "errorTitle": "المجتمع",
        "notFoundDescription": "لم نتمكن من العثور على c/{communityId}.",
        "notFoundTitle": "المجتمع غير موجود"
      },
      "settings": {
        "ageStatusLabel": "حالة العمر",
        "ageVerified": "تم التحقق من 18+",
        "appearanceSection": "المظهر",
        "appLanguageLabel": "لغة التطبيق",
        "avatarTitle": "الصورة الشخصية",
        "bioLabel": "النبذة",
        "connectedWalletsSection": "المحافظ المتصلة",
        "coverTitle": "الغلاف",
        "displayNameLabel": "اسم العرض",
        "displayNameRequired": "اسم العرض مطلوب.",
        "handleNoteEns": "ENS",
        "handleNoteEnsRefresh": "يحتاج ENS إلى تحديث",
        "handleNoteEnsUnverified": "ENS غير متحقق",
        "handleNotePirate": "معرّف بايرت",
        "identitySection": "الهوية",
        "languageSection": "اللغة",
        "linkedHandlesSection": "المعرّفات المرتبطة",
        "localeArabic": "العربية",
        "localeEnglish": "الإنجليزية",
        "localeMandarin": "الماندرين",
        "localePseudo": "الزائفة",
        "noConnectedWallets": "لا توجد محافظ متصلة بعد.",
        "notVerified": "غير متحقق",
        "noWalletConnected": "لا توجد محفظة متصلة",
        "postsAndCommentsLabel": "المنشورات والتعليقات",
        "postsAndCommentsNote": "التوقيع العام الأساسي",
        "preferencesTab": "التفضيلات",
        "primaryHandleLabel": "الأساسي",
        "primaryWalletLabel": "المحفظة الأساسية",
        "primaryWalletNote": "المحفظة الأساسية",
        "profileSection": "الملف الشخصي",
        "profileUpdated": "تم تحديث الملف الشخصي",
        "profileTab": "الملف الشخصي",
        "removeAvatar": "أزل الصورة الشخصية",
        "removeCover": "أزل الغلاف",
        "replaceAvatar": "استبدل الصورة الشخصية",
        "replaceCover": "استبدل الغلاف",
        "savePreferences": "احفظ التفضيلات",
        "saveProfile": "احفظ الملف الشخصي",
        "sectionsLabel": "أقسام الإعدادات",
        "selectLanguage": "اختر اللغة",
        "title": "الإعدادات",
        "uploadAvatar": "ارفع صورة شخصية",
        "uploadCover": "ارفع غلافًا",
        "preferencesUpdated": "تم تحديث التفضيلات",
        "walletTab": "المحفظة"
      },
      "notFound": {
        "body": "النسخة الأولى من الهيكل تثبّت فقط مجموعة صغيرة من المسارات: الرئيسية، الخلاصات، المجتمعات، المنشورات، الملفات الشخصية، الإعداد، عنصر نائب للوارد، وإنشاء مجتمع.",
        "description": "لا توجد صفحة مجهزة للمسار {path}.",
        "title": "المسار غير موجود"
      }
    },
    "shell": {
      "appHeader": {
        "connectLabel": "اتصل",
        "createEmptyLabel": "لا توجد مجتمعات حديثة.",
        "createLabel": "أنشئ",
        "createPickerTitle": "أنشئ منشورًا في",
        "homeAriaLabel": "اذهب إلى الصفحة الرئيسية",
        "notificationsAriaLabel": "الإشعارات",
        "openNavigationAriaLabel": "افتح التنقل",
        "profileAriaLabel": "افتح الملف الشخصي",
        "searchAriaLabel": "ابحث في بايرت",
        "searchPlaceholder": "ابحث في بايرت",
        "searchUnavailableToast": "البحث غير متاح بعد."
      },
      "appSidebar": {
        "brandLabel": "Pirate",
        "createCommunityLabel": "أنشئ مجتمعًا",
        "homeAriaLabel": "اذهب إلى الصفحة الرئيسية",
        "homeLabel": "الرئيسية",
        "resourcesLabel": "الموارد",
        "sections": [
          {
            "id": "recent",
            "label": "الأخيرة",
            "items": [
              {
                "id": "c/club1",
                "label": "c/النادي-١"
              },
              {
                "id": "c/pirate-radio",
                "label": "c/راديو-بايرت"
              }
            ]
          },
          {
            "id": "communities",
            "label": "المجتمعات",
            "items": [
              {
                "id": "c/builders",
                "label": "c/البناؤون"
              },
              {
                "id": "c/mixes",
                "label": "c/الميكسات"
              },
              {
                "id": "c/samples",
                "label": "c/السامبلز"
              }
            ]
          },
          {
            "id": "moderation",
            "label": "الإشراف",
            "items": [
              {
                "id": "c/pirate",
                "label": "c/بايرت"
              },
              {
                "id": "c/builders",
                "label": "c/البناؤون"
              }
            ]
          }
        ],
        "resourceItems": [
          {
            "id": "blog",
            "label": "المدونة"
          },
          {
            "id": "terms-of-service",
            "label": "شروط الخدمة"
          },
          {
            "id": "privacy-policy",
            "label": "سياسة الخصوصية"
          }
        ],
        "yourCommunitiesLabel": "مجتمعاتك"
      },
      "mobileFooter": {
        "createLabel": "أنشئ",
        "homeLabel": "الرئيسية",
        "inboxAriaLabel": "الوارد",
        "inboxLabel": "الوارد",
        "primaryNavAriaLabel": "التنقل الرئيسي",
        "profileAriaLabel": "الملف الشخصي",
        "profileLabel": "الملف الشخصي"
      },
      "storybook": {
        "contentAreaLabel": "منطقة المحتوى",
        "desktopHeaderBody": "الهيدر مستقل. كوّنه داخل غلاف التطبيق الحقيقي، وليس داخل بطاقات الإعداد.",
        "mobileHeaderBody": "الهيدر المحمول فقط.",
        "mobileFooterBody": "التذييل المحمول فقط.",
        "mobileChromeLead": "معاينة مستقلة لكروم التطبيق.",
        "mobileChromeFollow": "يبقى الهيدر والتذييل قابلين لإعادة الاستخدام ومنفصلين عن بطاقات الإعداد.",
        "standaloneDesktopSearchPlaceholder": "ابحث عن أي شيء"
      }
    }
  },
  "zh": {
    "routes": {
      "common": {
        "backHome": "返回首页",
        "bestTab": "最佳",
        "chooseCommunity": "选择社区",
        "commentsHeading": "评论",
        "createAction": "发布",
        "cancelReply": "取消",
        "joinedStatLabel": "加入时间",
        "loadMoreReplies": "加载更多回复",
        "loadReplies": "加载回复",
        "loadingReplies": "正在加载回复...",
        "newTab": "最新",
        "noComments": "还没有评论。",
        "noRecentCommunities": "还没有最近访问的社区。",
        "replyAction": "回复",
        "replyPlaceholder": "写回复",
        "showOriginal": "显示原文",
        "showTranslation": "显示翻译",
        "submitReply": "发布回复",
        "topAll": "全部时间",
        "topDay": "今天",
        "topHour": "这一小时",
        "topMonth": "本月",
        "topTab": "热门",
        "topWeek": "本周",
        "topYear": "今年"
      },
      "home": {
        "createCommunityLabel": "创建社区",
        "emptyHomeBody": "加入一个社区，或创建一个社区，开始建立你的首页动态。",
        "emptyHomeTitle": "还没有帖子",
        "emptyYourCommunitiesBody": "你创建或加入的社区会显示在这里。",
        "emptyYourCommunitiesTitle": "还没有社区",
        "membersLabel": "{count} 位成员",
        "railTitle": "最新帖子",
        "subtitle": "",
        "title": "首页"
      },
      "yourCommunities": {
        "gatedLabel": "受限",
        "openLabel": "公开",
        "railTitle": "你的空间",
        "subtitle": "面向成员的动态流外壳。移动端保持紧凑，把更重的导航交给侧边栏。",
        "title": "你的社区"
      },
      "post": {
        "commentsBody": "帖子串回复还未完整搭建。这个路由当前主要用于固定 `post_id` 读取的 URL 合约和页面框架。",
        "description": "为未来的 `GET /posts/{post_id}` 读取准备的单帖路由外壳。",
        "fallbackTitle": "帖子"
      },
      "community": {
        "aboutTab": "关于",
        "createPostLabel": "发布帖子",
        "feedTab": "动态",
        "membersLabel": "成员",
        "modToolsLabel": "管理工具",
        "requirementsLabel": "要求",
        "rulesLabel": "规则",
        "title": "社区"
      },
      "interactionGate": {
        "blockedReplyDescription": "这个社区的要求当前不允许你回复。",
        "blockedVoteDescription": "这个社区的要求当前不允许你投票。",
        "cantReplyHereTitle": "你不能在这里回复",
        "cantVoteHereTitle": "你不能在这里投票",
        "close": "关闭",
        "connectToContinue": "连接后继续。",
        "couldNotCheckRequirements": "无法检查这个社区的互动要求。",
        "joinInCommunity": "在 {communityName} 中{joinLabel}",
        "joinToReplyDescription": "在回复前，先在 {communityName} 中{joinLabel}。",
        "joinToReplyTitle": "{joinLabel}后回复",
        "joinToVoteDescription": "在投票前，先在 {communityName} 中{joinLabel}。",
        "joinToVoteTitle": "{joinLabel}后投票",
        "openCommunity": "打开 {communityName}",
        "readyDescription": "你可以在这里互动。",
        "readyTitle": "已就绪",
        "verifyInCommunity": "在 {communityName} 中验证",
        "verifyToReplyDescription": "完成身份验证后即可在这里回复。",
        "verifyToReplyTitle": "验证后回复",
        "verifyToVoteDescription": "完成身份验证后即可在这里投票。",
        "verifyToVoteTitle": "验证后投票",
        "bannedDescription": "你没有资格加入这个社区。"
      },
      "createPost": {
        "access": {
          "paidDescription": "动态里显示预览，购买后可解锁完整曲目。",
          "paidUnlock": "付费解锁",
          "public": "公开",
          "publicDescription": "任何人都可以播放完整曲目。",
          "rightsAttested": "我确认我有权发布并将此曲目商业化。",
          "useRegionalPricing": "使用社区区域定价"
        },
        "actions": {
          "post": "发布",
          "publishRemix": "发布混音"
        },
        "audience": {
          "private": "仅成员",
          "privateDescription": "只有已加入的成员可以阅读这条帖子。",
          "public": "公开",
          "publicDisabledReason": "这个社区已经限制了可阅读帖子的人群。",
          "publicDescription": "任何人都可以阅读这条帖子。"
        },
        "backToCommunity": "返回社区",
        "buttons": {
          "chooseFile": "选择文件",
          "clear": "清除",
          "replace": "替换"
        },
        "derivative": {
          "searchSourceTracks": "搜索源曲目"
        },
        "empty": {
          "noOptionalQualifiers": "这个社区没有可选的资格标签。",
          "noQualifiers": "未找到资格标签。",
          "noReferences": "还没有附加源作品。",
          "noSongs": "未找到歌曲。",
          "noSourceTracks": "未找到源曲目。"
        },
        "fields": {
          "audio": "音频",
          "body": "正文",
          "canvasVideo": "Canvas 视频",
          "caption": "说明",
          "commentary": "评论",
          "coverArt": "封面图",
          "genre": "流派",
          "image": "图片",
          "instrumentalStem": "伴奏分轨",
          "lyrics": "歌词",
          "primaryLanguage": "主要语言",
          "secondaryLanguage": "次要语言",
          "song": "歌曲",
          "title": "标题",
          "unlockPriceUsd": "解锁价格（美元）",
          "url": "链接",
          "video": "视频",
          "vocalStem": "人声分轨",
          "previewClip": "预览片段"
        },
        "identity": {
          "addQualifiers": "添加资格标签",
          "postAnonymously": "匿名发布",
          "qualifiersHelp": "为这条帖子附加已验证的资格标签。社区规则已隐含的标签不会重复显示。",
          "searchQualifiers": "搜索资格标签"
        },
        "labels": {
          "source": "来源"
        },
        "membershipRequiredDescription": "只有社区成员才能在这里发帖。",
        "membershipRequiredTitle": "发帖前先加入这个社区",
        "none": "无",
        "placeholders": {
          "artist": "艺人",
          "body": "写下你的帖子",
          "caption": "添加说明",
          "commentary": "添加评论",
          "lyrics": "粘贴歌词",
          "optional": "可选",
          "selectGenre": "选择流派",
          "selectLanguage": "选择语言",
          "songSearch": "搜索 Pirate 曲库",
          "songTitle": "歌曲标题",
          "sourceTrackSearch": "搜索 Pirate / Story 资产",
          "title": "标题",
          "unlockPrice": "1.00",
          "url": "https://"
        },
        "sections": {
          "access": "访问权限",
          "audience": "受众",
          "postAs": "发布身份",
          "qualifiers": "资格标签",
          "sourceTrack": "源曲目"
        },
        "setlist": {
          "cannotFindTrack": "找不到这首歌？",
          "hideManualDetails": "隐藏手动详情",
          "searchSongs": "为歌单项搜索歌曲"
        },
        "songModes": {
          "original": "原创",
          "remix": "混音"
        },
        "tabs": {
          "image": "图片",
          "link": "链接",
          "live": "直播",
          "song": "歌曲",
          "text": "文本",
          "video": "视频"
        },
        "title": "发布帖子",
        "upload": {
          "artworkHelp": "会显示在动态、发布页和播放器界面中。",
          "cover": "封面",
          "noFileSelected": "尚未选择文件",
          "squareArtwork": "上传方形封面图"
        }
      },
      "onboarding": {
        "actions": {
          "generateHandle": "生成新名称",
          "checkAgain": "重新检查",
          "continue": "继续",
          "getCode": "获取代码",
          "next": "下一步",
          "skip": "跳过"
        },
        "chooseNameAction": "选择名称",
        "description": "单一路由的引导流程，由客户端管理各阶段。嵌套引导 URL 还未固定。",
        "errors": {
          "chooseHandle": "继续前请先选择一个名称",
          "renameFailed": "名称修改失败"
        },
        "fields": {
          "handle": "名称",
          "redditCode": "Reddit {surface} 验证码",
          "redditUsername": "Reddit 用户名"
        },
        "importKarmaAction": "导入 Karma",
        "notes": {
          "addCodeToProfile": "把这段代码添加到你的 Reddit 个人资料简介中：",
          "checkedRedditAt": "已在 {time} 检查 Reddit。代码还没有显示出来。保存个人资料后，等待几秒，再点击“重新检查”。",
          "checkingRedditNow": "正在检查 Reddit...",
          "handleAvailable": "{handle}.pirate 可用",
          "handleTaken": "{handle}.pirate 已被占用",
          "importing": "正在导入...",
          "noSuggestionsYet": "还没有推荐社区。之后可以从你的 feed 中加入。",
          "saveProfileThenCheckAgain": "保存 Reddit 个人资料简介后，等待几秒，再点击“重新检查”。",
          "startingImport": "正在启动导入..."
        },
        "placeholders": {
          "handle": "选择你的名称"
        },
        "progressLabel": "引导流程",
        "stepCount": "{current}/{total}",
        "suggestedCommunitiesAction": "推荐社区",
        "surfaces": {
          "about": "关于",
          "bio": "简介",
          "profile": "个人资料"
        },
        "title": "完成你的 Pirate 身份设置"
      },
      "inbox": {
        "body": "在通知或消息系统成为真实产品界面前，先把 `/inbox` 保持为中性的占位页。",
        "description": "这个路由已搭好外壳，这样移动端导航就能指向一个真实存在的位置，同时保留收件箱行为的后续定义空间。",
        "emptyState": "还没有通知",
        "loading": "加载中...",
        "recentActivity": "最近动态",
        "someone": "有人",
        "taskActionNeeded": "需要处理",
        "taskDismiss": "忽略",
        "taskNamespaceVerificationRequired": "验证你的社区命名空间",
        "taskVerify": "验证",
        "title": "收件箱"
      },
      "createCommunity": {
        "reopenVerification": "重新打开验证",
        "description": "围绕现有社区创建组件搭建的页面外壳，提交流程暂未接通。",
        "startVerification": "验证",
        "title": "创建社区",
        "verifyDescription": "创建社区前请先完成验证。",
        "verifyPendingDescription": "完成掌纹扫描后继续。",
        "verifyPendingTitle": "完成验证",
        "verifyStartDescription": "扫描你的手掌以证明你是真人。不会保存照片或数据。",
        "verifyStartTitle": "验证"
      },
      "profile": {
        "commentsTab": "评论",
        "editProfile": "编辑资料",
        "emptyActivity": "还没有动态。",
        "emptyPosts": "还没有帖子。",
        "emptyScrobbles": "还没有 Scrobble。",
        "follow": "关注",
        "followersLabel": "关注者",
        "following": "已关注",
        "followingLabel": "关注中",
        "handleUpdated": "用户名已更新",
        "message": "发消息",
        "moreActions": "更多操作",
        "overviewTab": "概览",
        "postsTab": "帖子",
        "scrobblesTab": "Scrobbles",
        "shareProfile": "分享资料",
        "title": "个人资料",
        "verificationTitle": "验证",
        "walletTitle": "钱包"
      },
      "publicProfile": {
        "aboutTab": "关于",
        "communitiesTitle": "社区",
        "emptyAbout": "还没有资料。",
        "emptyPosts": "还没有帖子。",
        "emptyScrobbles": "还没有 Scrobble。",
        "emptySongs": "还没有歌曲。",
        "emptyVideos": "还没有视频。",
        "errorDescription": "当前无法加载这个公开资料页。",
        "errorTitle": "公开资料页",
        "joinedLabel": "加入时间",
        "notFoundDescription": "找不到 {path} 的公开资料页。",
        "notFoundTitle": "找不到个人资料",
        "openInPirate": "在 Pirate 中打开",
        "postsTab": "帖子",
        "scrobblesTab": "Scrobbles",
        "songsTab": "歌曲",
        "videosTab": "视频"
      },
      "publicCommunity": {
        "emptyPosts": "还没有帖子",
        "errorDescription": "当前无法加载这个社区。",
        "errorTitle": "社区",
        "notFoundDescription": "找不到 c/{communityId}。",
        "notFoundTitle": "找不到社区"
      },
      "settings": {
        "ageStatusLabel": "年龄状态",
        "ageVerified": "已完成 18+ 验证",
        "appearanceSection": "外观",
        "appLanguageLabel": "应用语言",
        "avatarTitle": "头像",
        "bioLabel": "简介",
        "connectedWalletsSection": "已连接的钱包",
        "coverTitle": "封面",
        "displayNameLabel": "显示名称",
        "displayNameRequired": "显示名称为必填项。",
        "handleNoteEns": "ENS",
        "handleNoteEnsRefresh": "ENS 需要刷新",
        "handleNoteEnsUnverified": "ENS 未验证",
        "handleNotePirate": "Pirate 用户名",
        "identitySection": "身份",
        "languageSection": "语言",
        "linkedHandlesSection": "已关联用户名",
        "localeArabic": "阿拉伯语",
        "localeEnglish": "英语",
        "localeMandarin": "中文",
        "localePseudo": "伪本地化",
        "noConnectedWallets": "还没有已连接的钱包。",
        "notVerified": "未验证",
        "noWalletConnected": "未连接钱包",
        "postsAndCommentsLabel": "帖子和评论",
        "postsAndCommentsNote": "默认公开署名",
        "preferencesTab": "偏好",
        "primaryHandleLabel": "主用",
        "primaryWalletLabel": "主钱包",
        "primaryWalletNote": "主钱包",
        "profileSection": "个人资料",
        "profileUpdated": "资料已更新",
        "profileTab": "个人资料",
        "removeAvatar": "移除头像",
        "removeCover": "移除封面",
        "replaceAvatar": "更换头像",
        "replaceCover": "更换封面",
        "savePreferences": "保存偏好",
        "saveProfile": "保存资料",
        "sectionsLabel": "设置分区",
        "selectLanguage": "选择语言",
        "title": "设置",
        "uploadAvatar": "上传头像",
        "uploadCover": "上传封面",
        "preferencesUpdated": "偏好已更新",
        "walletTab": "钱包"
      },
      "notFound": {
        "body": "当前脚手架只固定了一小部分路由：首页、信息流、社区、帖子、个人资料、引导、收件箱占位页和创建社区。",
        "description": "没有为 {path} 提供已搭建的页面。",
        "title": "找不到路由"
      }
    },
    "shell": {
      "appHeader": {
        "connectLabel": "连接",
        "createEmptyLabel": "最近没有社区。",
        "createLabel": "发布",
        "createPickerTitle": "选择要发布到的社区",
        "homeAriaLabel": "返回首页",
        "notificationsAriaLabel": "通知",
        "openNavigationAriaLabel": "打开导航",
        "profileAriaLabel": "打开个人资料",
        "searchAriaLabel": "搜索 Pirate",
        "searchPlaceholder": "搜索 Pirate",
        "searchUnavailableToast": "搜索功能暂未开放。"
      },
      "appSidebar": {
        "brandLabel": "Pirate",
        "createCommunityLabel": "创建社区",
        "homeAriaLabel": "返回首页",
        "homeLabel": "首页",
        "resourcesLabel": "资源",
        "sections": [
          {
            "id": "recent",
            "label": "最近访问",
            "items": [
              {
                "id": "c/club1",
                "label": "c/俱乐部1"
              },
              {
                "id": "c/pirate-radio",
                "label": "c/海盗电台"
              }
            ]
          },
          {
            "id": "communities",
            "label": "社区",
            "items": [
              {
                "id": "c/builders",
                "label": "c/创作者"
              },
              {
                "id": "c/mixes",
                "label": "c/混音"
              },
              {
                "id": "c/samples",
                "label": "c/采样"
              }
            ]
          },
          {
            "id": "moderation",
            "label": "管理",
            "items": [
              {
                "id": "c/pirate",
                "label": "c/海盗"
              },
              {
                "id": "c/builders",
                "label": "c/创作者"
              }
            ]
          }
        ],
        "resourceItems": [
          {
            "id": "blog",
            "label": "博客"
          },
          {
            "id": "terms-of-service",
            "label": "服务条款"
          },
          {
            "id": "privacy-policy",
            "label": "隐私政策"
          }
        ],
        "yourCommunitiesLabel": "你的社区"
      },
      "mobileFooter": {
        "createLabel": "发布",
        "homeLabel": "首页",
        "inboxAriaLabel": "收件箱",
        "inboxLabel": "收件箱",
        "primaryNavAriaLabel": "主导航",
        "profileAriaLabel": "个人资料",
        "profileLabel": "我的"
      },
      "storybook": {
        "contentAreaLabel": "内容区域",
        "desktopHeaderBody": "页头应独立使用。把它放进真实应用外壳，不要塞进引导卡片。",
        "mobileHeaderBody": "仅移动端页头。",
        "mobileFooterBody": "仅移动端底部导航。",
        "mobileChromeLead": "独立外壳预览。",
        "mobileChromeFollow": "页头和底部导航应保持可复用，并与引导流程分离。",
        "standaloneDesktopSearchPlaceholder": "搜索任何内容"
      }
    }
  }
} as const;

export type RealLocaleCode = (typeof REAL_LOCALE_CODES)[number];
export type LocaleNamespace = (typeof LOCALE_NAMESPACES)[number];
export type GeneratedLocaleCatalogs = typeof GENERATED_LOCALE_CATALOGS;
