// Build provenance embedded in the published tarball at pack time. Separated from
// the main `.` entry so local workspace consumers (the `web` repo) that never
// need /__version are unaffected; only `@pirate/karaoke-runtime/build` requires it.
//
// `build-info.json` is generated by `scripts/build-provenance.ts` (prepack) and
// shipped in the published tarball. The API build re-exports KARAOKE_RUNTIME_BUILD
// onto worker build vars surfaced on /__version (spec §9a provenance).
import buildInfo from "../build-info.json" with { type: "json" };

export const KARAOKE_RUNTIME_BUILD = {
  version: buildInfo.version,
  gitSha: buildInfo.gitSha,
} as const;

export type KaraokeRuntimeBuild = typeof KARAOKE_RUNTIME_BUILD;