import { readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, extname, join } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const projectRoot = dirname(scriptDir);
const localesRoot = join(projectRoot, "src", "locales");
const outputFile = join(localesRoot, "generated.ts");

function isPlainObject(value) {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

function describeType(value) {
  if (Array.isArray(value)) return "array";
  if (value === null) return "null";
  return typeof value;
}

function validateLocaleShape(baseValue, localeValue, path) {
  const baseType = describeType(baseValue);
  const localeType = describeType(localeValue);

  if (baseType !== localeType) {
    throw new Error(
      `Locale catalog mismatch at ${path}: expected ${baseType}, received ${localeType}.`,
    );
  }

  if (Array.isArray(baseValue)) {
    if (baseValue.length !== localeValue.length) {
      throw new Error(
        `Locale catalog mismatch at ${path}: expected array length ${baseValue.length}, received ${localeValue.length}.`,
      );
    }

    for (let index = 0; index < baseValue.length; index += 1) {
      validateLocaleShape(baseValue[index], localeValue[index], `${path}[${index}]`);
    }

    return;
  }

  if (isPlainObject(baseValue)) {
    const baseKeys = Object.keys(baseValue).sort();
    const localeKeys = Object.keys(localeValue).sort();

    if (baseKeys.join("\0") !== localeKeys.join("\0")) {
      throw new Error(
        `Locale catalog mismatch at ${path}: expected keys [${baseKeys.join(", ")}], received [${localeKeys.join(", ")}].`,
      );
    }

    for (const key of baseKeys) {
      validateLocaleShape(baseValue[key], localeValue[key], `${path}.${key}`);
    }
  }
}

async function readJsonCatalog(path) {
  const source = await readFile(path, "utf8");
  return JSON.parse(source);
}

async function main() {
  const directoryEntries = await readdir(localesRoot, { withFileTypes: true });
  const localeDirs = directoryEntries
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort((left, right) => {
      if (left === "en") return -1;
      if (right === "en") return 1;
      return left.localeCompare(right);
    });

  if (!localeDirs.includes("en")) {
    throw new Error("Missing canonical English locale directory at src/locales/en.");
  }

  const englishEntries = await readdir(join(localesRoot, "en"), { withFileTypes: true });
  const namespaces = englishEntries
    .filter((entry) => entry.isFile() && extname(entry.name) === ".json")
    .map((entry) => entry.name.replace(/\.json$/u, ""))
    .sort();

  if (namespaces.length === 0) {
    throw new Error("No locale namespaces found in src/locales/en.");
  }

  const catalogs = {};
  const englishCatalogs = {};

  for (const namespace of namespaces) {
    englishCatalogs[namespace] = await readJsonCatalog(
      join(localesRoot, "en", `${namespace}.json`),
    );
  }

  for (const locale of localeDirs) {
    const localeEntries = await readdir(join(localesRoot, locale), { withFileTypes: true });
    const localeNamespaces = localeEntries
      .filter((entry) => entry.isFile() && extname(entry.name) === ".json")
      .map((entry) => entry.name.replace(/\.json$/u, ""))
      .sort();

    if (localeNamespaces.join("\0") !== namespaces.join("\0")) {
      throw new Error(
        `Locale ${locale} does not match English namespaces. Expected [${namespaces.join(", ")}], received [${localeNamespaces.join(", ")}].`,
      );
    }

    catalogs[locale] = {};

    for (const namespace of namespaces) {
      const localeCatalog = await readJsonCatalog(
        join(localesRoot, locale, `${namespace}.json`),
      );
      validateLocaleShape(englishCatalogs[namespace], localeCatalog, `${locale}.${namespace}`);
      catalogs[locale][namespace] = localeCatalog;
    }
  }

  const content = `// This file is generated by \`bun run locales:generate\`. Do not edit manually.

export const REAL_LOCALE_CODES = ${JSON.stringify(localeDirs)} as const;
export const LOCALE_NAMESPACES = ${JSON.stringify(namespaces)} as const;

export const GENERATED_LOCALE_CATALOGS = ${JSON.stringify(catalogs, null, 2)} as const;

export type RealLocaleCode = (typeof REAL_LOCALE_CODES)[number];
export type LocaleNamespace = (typeof LOCALE_NAMESPACES)[number];
export type GeneratedLocaleCatalogs = typeof GENERATED_LOCALE_CATALOGS;
`;

  try {
    const existing = await readFile(outputFile, "utf8");
    if (existing === content) return;
  } catch {}
  await writeFile(outputFile, content);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
});
