import { readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const localesRoot = resolve(root, "src/locales");
const outputPath = resolve(localesRoot, "generated.ts");
const locales = ["en", "ar", "zh"];

function shapeOf(value) {
  if (Array.isArray(value)) return value.map(shapeOf);
  if (value && typeof value === "object") {
    return Object.fromEntries(Object.keys(value).sort().map(key => [key, shapeOf(value[key])]));
  }
  return typeof value;
}

function stable(value) {
  if (Array.isArray(value)) return value.map(stable);
  if (value && typeof value === "object") {
    return Object.fromEntries(Object.keys(value).sort().map(key => [key, stable(value[key])]));
  }
  return value;
}

const catalogs = {};
let namespaces;
let referenceShape;

for (const locale of locales) {
  const files = (await readdir(resolve(localesRoot, locale)))
    .filter(file => file.endsWith(".json"))
    .sort();
  const currentNamespaces = files.map(file => file.slice(0, -5));
  namespaces ??= currentNamespaces;
  if (JSON.stringify(currentNamespaces) !== JSON.stringify(namespaces)) {
    throw new Error(`${locale} locale namespaces differ from en`);
  }

  catalogs[locale] = {};
  for (const file of files) {
    const namespace = file.slice(0, -5);
    const source = await readFile(resolve(localesRoot, locale, file), "utf8");
    const messages = JSON.parse(source);
    catalogs[locale][namespace] = stable(messages);
  }

  const shape = shapeOf(catalogs[locale]);
  referenceShape ??= shape;
  if (JSON.stringify(shape) !== JSON.stringify(referenceShape)) {
    throw new Error(`${locale} locale message shape differs from en`);
  }
}

const banner = `// Generated by ${relative(root, fileURLToPath(import.meta.url))}. Do not edit.\n`;
const source = `${banner}export const GENERATED_LOCALE_CATALOGS = ${JSON.stringify(stable(catalogs), null, 2)} as const;\n\nexport type GeneratedLocaleCatalogs = typeof GENERATED_LOCALE_CATALOGS;\nexport type RealLocaleCode = keyof GeneratedLocaleCatalogs;\nexport type LocaleNamespace = keyof GeneratedLocaleCatalogs["en"];\n`;
await writeFile(outputPath, source);
