import type { AppRoute } from "@/app/router";

// Keep this exhaustive so every new route kind must choose a spacing owner.
const ROUTE_CONTENT_SPACING: Record<AppRoute["kind"], boolean> = {
  home: true,
  live: false,
  "community-feed": true,
  popular: true,
  "public-profile": false,
  "public-agent": false,
  "your-communities": false,
  wallet: true,
  "booking-host-settings": true,
  "settings-index": false,
  settings: false,
  "create-post": false,
  "create-post-global": false,
  "community-moderation-index": false,
  "community-moderation": false,
  "community-landing": false,
  "community-videos": true,
  community: false,
  "booking-public": true,
  "booking-checkout": true,
  "booking-management": true,
  "booking-session": true,
  "create-community": false,
  post: false,
  "post-replay-draft": false,
  "post-karaoke": false,
  "post-karaoke-leaderboard": false,
  "post-study": false,
  "post-streaks": false,
  "live-room": false,
  crosspost: false,
  inbox: false,
  chat: false,
  "chat-new": false,
  "chat-conversation": false,
  "chat-target": false,
  advertise: false,
  me: false,
  onboarding: false,
  "authorize-device": false,
  "telegram-account-link": false,
  "telegram-mini-app": false,
  "telegram-exchange": false,
  "telegram-self-return": false,
  "telegram-join": false,
  "telegram-verify": false,
  "telegram-community": false,
  "telegram-post": false,
  "telegram-study": false,
  "not-found": false,
};

export function routeOwnsContentSpacing(route: Pick<AppRoute, "kind">): boolean {
  return ROUTE_CONTENT_SPACING[route.kind];
}
