// Generated by scripts/generate-locales.mjs. Do not edit.
export const GENERATED_LOCALE_CATALOGS = {
  "ar": {
    "feed": {
      "byAuthor": "بواسطة {author}",
      "empty": "لا توجد فيديوهات عامة حتى الآن.",
      "fallbackAuthor": "منشئ عام",
      "fallbackTitle": "فيديو عام",
      "label": "موجز الفيديو العام",
      "likeRequiresSession": "إعجاب · اتصل للتفاعل",
      "loadMore": "تحميل المزيد من الفيديوهات",
      "loadingMore": "جارٍ تحميل المزيد",
      "paginationError": "تعذر تحميل المزيد من الفيديوهات.",
      "pause": "إيقاف مؤقت",
      "play": "تشغيل",
      "retry": "إعادة المحاولة",
      "unavailable": "موجز الفيديو العام غير متاح.",
      "videoBy": "فيديو بواسطة {author}",
      "videoDescription": "وصف الفيديو",
      "videoLabel": "فيديو {title}"
    },
    "routes": {
      "home": {
        "description": "موجز فيديو بايرت ويب",
        "heading": "واجهة بايرت ويب",
        "title": "الرئيسية · بايرت ويب"
      },
      "moderation": {
        "links": {
          "addLink": "أضف رابطًا",
          "displayNamePlaceholder": "اسم العرض",
          "emptyState": "لا توجد روابط بعد.",
          "labelLabel": "التسمية",
          "platformLabel": "المنصة",
          "title": "الروابط",
          "urlLabel": "الرابط",
          "urlPlaceholder": "https://"
        },
        "rules": {
          "addRule": "إضافة قاعدة",
          "defaultRule1Body": "لا تحرش ولا خطاب كراهية ولا سلوك سامي. عامل جميع المساهمين والأعضاء بلطف.",
          "defaultRule1Title": "احترام الآخرين والالتزام بالأدب",
          "defaultRule2Body": "الإفراط في الترويج والرسائل المزعجة والإعلانات غير مسموح به بأي شكل.",
          "defaultRule2Title": "لا رسائل مزعجة",
          "description": "تحدد القواعد التوقعات للأعضاء والزوار في مجتمعك.",
          "descriptionPlaceholder": "الوصف",
          "emptyState": "لا توجد قواعد بعد.",
          "maxChars100": "الحد الأقصى 100 حرف",
          "maxChars500": "الحد الأقصى 500 حرف",
          "namePlaceholder": "اسم القاعدة",
          "reportReasonHint": "افتراضيًا، هذا هو نفس اسم قاعدتك.",
          "reportReasonPlaceholder": "سبب الإبلاغ",
          "reportingDescription": "يمكن للمستخدمين أو المشرفين اختيار سبب إبلاغ عند الإبلاغ عن محتوى.",
          "reportingTitle": "الإبلاغ",
          "title": "القواعد"
        },
        "saveFooter": {
          "defaultSaveLabel": "حفظ"
        }
      },
      "notFound": {
        "description": "المسار المطلوب غير موجود.",
        "returnHome": "العودة إلى الرئيسية",
        "title": "غير موجود"
      },
      "profile": {
        "createdCommunities": "المجتمعات التي تم إنشاؤها",
        "createdCommunityPluralDescription": "أنشأ {name} عدد {count} من المجتمعات على Pirate Web.",
        "createdCommunitySingularDescription": "أنشأ {name} مجتمعًا واحدًا على Pirate Web.",
        "defaultDescription": "الملف الشخصي العام لـ {name} على Pirate Web.",
        "emptyCommunities": "لم يتم إنشاء مجتمعات بعد.",
        "error": "الملف الشخصي غير متاح مؤقتًا.",
        "heading": "الملف الشخصي: @{handle}",
        "invalid": "اسم الملف الشخصي غير صالح.",
        "loading": "جارٍ تحميل الملف الشخصي",
        "notFound": "تعذر العثور على هذا الملف الشخصي.",
        "openCommunity": "فتح {name}",
        "title": "@{handle} · بايرت ويب"
      },
      "settings": {
        "booking": {
          "addAvailability": "إضافة",
          "addException": "إضافة",
          "addPriceRule": "إضافة",
          "allDays": "كل الأيام",
          "anyTime": "أي وقت",
          "autosaveNote": "تُحفظ التغييرات تلقائيًا.",
          "basePriceLabel": "السعر الأساسي (USDC)",
          "bookableLabel": "قابل للحجز",
          "bookableNoAvailability": "الحجز مفعّل، لكنك غير مرئي بعد — أضف توافرًا أسبوعيًا أدناه لتظهر في البحث والخلاصة.",
          "bookableOffHint": "لست قابلًا للحجز بعد — فعّله عندما تكون جاهزًا.",
          "bookableOnHint": "يمكن للأشخاص حجزك. أوقفه مؤقتًا دون فقدان جدولك.",
          "cancellationCopy": "يحصل الحاجزون الذين يلغون خلال 24 ساعة من الحجز على استرداد كامل؛ أما الإلغاءات اللاحقة فلا تُرد. إذا ألغيت أنت (المضيف) أو لم تحضر، يحصل الحاجز على استرداد كامل.",
          "cancellationTitle": "سياسة الإلغاء",
          "durationLabel": "مدة الجلسة",
          "durationMinutes": "{count} دقيقة",
          "exceptionBlock": "حظر",
          "exceptionOpen": "فتح",
          "exceptionsTitle": "استثناءات لمرة واحدة",
          "intro": "اسمح للأشخاص بحجز جلسات فيديو 1:1 مدفوعة معك. حدد توافرك وسعرك، ثم فعّل قابلية الحجز ليتمكنوا من حجزك من رابط ملفك الشخصي.",
          "navDescription": "حدّد جدول جلسات 1:1 المدفوعة والتسعير والتوافر.",
          "navLabel": "الحجوزات",
          "noAvailability": "لا يوجد توافر بعد — أضف فترة أسبوعية متكررة أدناه.",
          "noExceptions": "ينطبق التوافر المتكرر كما هو.",
          "noPriceRules": "ينطبق السعر الأساسي على كل وقت متاح.",
          "publish": "نشر الحجوزات",
          "publishBlockedNote": "أعدّ محفظة التطبيق لتلقي المدفوعات.",
          "publishLiveNote": "يمكن لأي شخص لديه رابط ملفك الشخصي حجز وقت متاح.",
          "publishReadyNote": "أنت جاهز — انشر ليتمكن الأشخاص من حجزك.",
          "publishTitleIdle": "انشر حجوزاتك",
          "publishTitleLive": "حجوزاتك مفعّلة",
          "rangeSeparator": "إلى",
          "remove": "إزالة",
          "saveSettings": "حفظ",
          "savingNote": "جارٍ الحفظ…",
          "sectionTitle": "حجوزات 1:1 مدفوعة",
          "timezoneLabel": "المنطقة الزمنية",
          "unpublish": "إلغاء النشر",
          "variablePricingTitle": "تسعير متغير",
          "weeklyAvailabilityTitle": "التوافر الأسبوعي"
        }
      }
    },
    "shell": {
      "appName": "بايرت ويب",
      "error": {
        "title": "واجهة التطبيق غير متاحة"
      },
      "navigation": {
        "community": "المجتمع",
        "home": "الرئيسية",
        "settings": "الإعدادات"
      }
    }
  },
  "en": {
    "feed": {
      "byAuthor": "by {author}",
      "empty": "No public videos are available yet.",
      "fallbackAuthor": "public creator",
      "fallbackTitle": "Public video",
      "label": "Public video feed",
      "likeRequiresSession": "Like · connect to act",
      "loadMore": "Load more videos",
      "loadingMore": "Loading more",
      "paginationError": "More videos could not be loaded.",
      "pause": "Pause",
      "play": "Play",
      "retry": "Retry",
      "unavailable": "The public video feed is unavailable.",
      "videoBy": "Video by {author}",
      "videoDescription": "Video description",
      "videoLabel": "{title} video"
    },
    "routes": {
      "home": {
        "description": "Pirate Web video feed",
        "heading": "Pirate Web Solid shell",
        "title": "Home · Pirate Web"
      },
      "moderation": {
        "links": {
          "addLink": "Add link",
          "displayNamePlaceholder": "Display name",
          "emptyState": "No links yet.",
          "labelLabel": "Label",
          "platformLabel": "Platform",
          "title": "Links",
          "urlLabel": "URL",
          "urlPlaceholder": "https://"
        },
        "rules": {
          "addRule": "Add rule",
          "defaultRule1Body": "No harassment, hate speech, or toxic behavior. Treat all contributors and members with kindness.",
          "defaultRule1Title": "Respect others and be civil",
          "defaultRule2Body": "Excessive promotion, spam, or advertising of any kind is not allowed.",
          "defaultRule2Title": "No spam",
          "description": "Rules set the expectations for members and visitors in your community.",
          "descriptionPlaceholder": "Description",
          "emptyState": "No rules yet.",
          "maxChars100": "Max characters 100",
          "maxChars500": "Max characters 500",
          "namePlaceholder": "Rule name",
          "reportReasonHint": "By default, this is the same as your rule name.",
          "reportReasonPlaceholder": "Report reason",
          "reportingDescription": "Users or mods can select a report reason when reporting content.",
          "reportingTitle": "Reporting",
          "title": "Rules"
        },
        "saveFooter": {
          "defaultSaveLabel": "Save"
        }
      },
      "notFound": {
        "description": "The requested route does not exist.",
        "returnHome": "Return home",
        "title": "Not found"
      },
      "profile": {
        "createdCommunities": "Created communities",
        "createdCommunityPluralDescription": "{name} created {count} communities on Pirate Web.",
        "createdCommunitySingularDescription": "{name} created 1 community on Pirate Web.",
        "defaultDescription": "Public profile for {name} on Pirate Web.",
        "emptyCommunities": "No communities created yet.",
        "error": "This profile is temporarily unavailable.",
        "heading": "Profile: @{handle}",
        "invalid": "That profile handle is not valid.",
        "loading": "Loading profile",
        "notFound": "This profile could not be found.",
        "openCommunity": "Open {name}",
        "title": "@{handle} · Pirate Web"
      },
      "settings": {
        "booking": {
          "addAvailability": "Add",
          "addException": "Add",
          "addPriceRule": "Add",
          "allDays": "All days",
          "anyTime": "Any",
          "autosaveNote": "Changes save automatically.",
          "basePriceLabel": "Base price (USDC)",
          "bookableLabel": "Bookable",
          "bookableNoAvailability": "Bookable is on, but you're not visible yet — add weekly availability below to appear in search and feed.",
          "bookableOffHint": "You're not bookable yet — turn on when you're ready.",
          "bookableOnHint": "People can book you. Turn off to pause without losing your schedule.",
          "cancellationCopy": "Bookers receive a full refund when they cancel at least 24 hours before the session starts. Cancellations made less than 24 hours before the session are non-refundable. If you (the host) cancel or do not attend, the booker receives a full refund.",
          "cancellationTitle": "Cancellation policy",
          "durationLabel": "Session length",
          "durationMinutes": "{count} minutes",
          "exceptionBlock": "Block",
          "exceptionOpen": "Open",
          "exceptionsTitle": "One-off exceptions",
          "intro": "Let people book paid 1:1 video sessions with you. Set your availability and price, then turn on Bookable to become bookable from your profile link.",
          "navDescription": "Set your paid 1:1 schedule, pricing, and availability.",
          "navLabel": "Bookings",
          "noAvailability": "No availability yet — add a recurring weekly window below.",
          "noExceptions": "Recurring availability applies as-is.",
          "noPriceRules": "Base price applies to every available slot.",
          "publish": "Publish bookings",
          "publishBlockedNote": "Set up your app wallet to receive payouts.",
          "publishLiveNote": "Anyone with your profile link can book an available slot.",
          "publishReadyNote": "You're ready — publish to let people book you.",
          "publishTitleIdle": "Publish your bookings",
          "publishTitleLive": "Your bookings are live",
          "rangeSeparator": "to",
          "remove": "Remove",
          "saveSettings": "Save",
          "savingNote": "Saving…",
          "sectionTitle": "Paid 1:1 bookings",
          "timezoneLabel": "Timezone",
          "unpublish": "Unpublish",
          "variablePricingTitle": "Variable pricing",
          "weeklyAvailabilityTitle": "Weekly availability"
        }
      }
    },
    "shell": {
      "appName": "Pirate Web",
      "error": {
        "title": "App shell unavailable"
      },
      "navigation": {
        "community": "Community",
        "home": "Home",
        "settings": "Settings"
      }
    }
  },
  "zh": {
    "feed": {
      "byAuthor": "作者：{author}",
      "empty": "暂时没有公开视频。",
      "fallbackAuthor": "公开视频作者",
      "fallbackTitle": "公开视频",
      "label": "公开视频动态",
      "likeRequiresSession": "点赞 · 登录后操作",
      "loadMore": "加载更多视频",
      "loadingMore": "正在加载更多",
      "paginationError": "无法加载更多视频。",
      "pause": "暂停",
      "play": "播放",
      "retry": "重试",
      "unavailable": "公开视频动态暂不可用。",
      "videoBy": "{author} 的视频",
      "videoDescription": "视频描述",
      "videoLabel": "{title} 视频"
    },
    "routes": {
      "home": {
        "description": "Pirate Web 视频动态",
        "heading": "Pirate Web Solid 界面",
        "title": "首页 · Pirate Web"
      },
      "moderation": {
        "links": {
          "addLink": "添加链接",
          "displayNamePlaceholder": "显示名称",
          "emptyState": "还没有链接。",
          "labelLabel": "标签",
          "platformLabel": "平台",
          "title": "链接",
          "urlLabel": "链接",
          "urlPlaceholder": "https://"
        },
        "rules": {
          "addRule": "添加规则",
          "defaultRule1Body": "禁止骚扰、仇恨言论或任何有害行为。请友善对待所有贡献者和成员。",
          "defaultRule1Title": "尊重他人，文明交流",
          "defaultRule2Body": "不允许任何形式的过度推广、垃圾信息或广告。",
          "defaultRule2Title": "禁止垃圾信息",
          "description": "规则为社区中的成员和访客设定期望。",
          "descriptionPlaceholder": "描述",
          "emptyState": "还没有规则。",
          "maxChars100": "最多 100 个字符",
          "maxChars500": "最多 500 个字符",
          "namePlaceholder": "规则名称",
          "reportReasonHint": "默认情况下，这与你的规则名称相同。",
          "reportReasonPlaceholder": "举报原因",
          "reportingDescription": "用户或版主在举报内容时可以选择举报原因。",
          "reportingTitle": "举报",
          "title": "规则"
        },
        "saveFooter": {
          "defaultSaveLabel": "保存"
        }
      },
      "notFound": {
        "description": "请求的页面不存在。",
        "returnHome": "返回首页",
        "title": "未找到"
      },
      "profile": {
        "createdCommunities": "已创建的社区",
        "createdCommunityPluralDescription": "{name} 在 Pirate Web 创建了 {count} 个社区。",
        "createdCommunitySingularDescription": "{name} 在 Pirate Web 创建了 1 个社区。",
        "defaultDescription": "{name} 在 Pirate Web 的公开个人资料。",
        "emptyCommunities": "尚未创建社区。",
        "error": "该个人资料暂时不可用。",
        "heading": "个人资料：@{handle}",
        "invalid": "该个人资料句柄无效。",
        "loading": "正在加载个人资料",
        "notFound": "找不到该个人资料。",
        "openCommunity": "打开 {name}",
        "title": "@{handle} · Pirate Web"
      },
      "settings": {
        "booking": {
          "addAvailability": "添加",
          "addException": "添加",
          "addPriceRule": "添加",
          "allDays": "所有日期",
          "anyTime": "任意时间",
          "autosaveNote": "更改会自动保存。",
          "basePriceLabel": "基础价格 (USDC)",
          "bookableLabel": "可预约",
          "bookableNoAvailability": "可预约已开启，但你还不会显示 — 在下方添加每周重复时段，才会出现在搜索和动态中。",
          "bookableOffHint": "你还不可预约 — 准备好后再开启。",
          "bookableOnHint": "人们可以预约你。关闭后可暂停预约，且不会丢失你的日程。",
          "cancellationCopy": "预约者在预约后 24 小时内取消可获得全额退款；之后取消不予退款。如果你（主持人）取消或未出席，预约者将获得全额退款。",
          "cancellationTitle": "取消政策",
          "durationLabel": "会话时长",
          "durationMinutes": "{count} 分钟",
          "exceptionBlock": "屏蔽",
          "exceptionOpen": "开放",
          "exceptionsTitle": "一次性例外",
          "intro": "让人们预约与你进行付费 1:1 视频会话。设置可预约时间和价格，然后开启“可预约”，即可通过你的个人资料链接接受预约。",
          "navDescription": "设置你的付费 1:1 日程、价格和可预约时间。",
          "navLabel": "预约",
          "noAvailability": "还没有可预约时间 — 在下方添加一个每周重复时段。",
          "noExceptions": "重复可预约时间将照常适用。",
          "noPriceRules": "基础价格适用于所有可预约时段。",
          "publish": "发布预约",
          "publishBlockedNote": "设置你的应用钱包以接收款项。",
          "publishLiveNote": "拥有你个人资料链接的任何人都可以预约可用时段。",
          "publishReadyNote": "你已准备好 — 发布后人们就可以预约你。",
          "publishTitleIdle": "发布你的预约",
          "publishTitleLive": "你的预约已上线",
          "rangeSeparator": "至",
          "remove": "移除",
          "saveSettings": "保存",
          "savingNote": "正在保存…",
          "sectionTitle": "付费 1:1 预约",
          "timezoneLabel": "时区",
          "unpublish": "取消发布",
          "variablePricingTitle": "浮动定价",
          "weeklyAvailabilityTitle": "每周可预约时间"
        }
      }
    },
    "shell": {
      "appName": "Pirate Web",
      "error": {
        "title": "应用界面暂不可用"
      },
      "navigation": {
        "community": "社区",
        "home": "首页",
        "settings": "设置"
      }
    }
  }
} as const;

export type GeneratedLocaleCatalogs = typeof GENERATED_LOCALE_CATALOGS;
export type RealLocaleCode = keyof GeneratedLocaleCatalogs;
export type LocaleNamespace = keyof GeneratedLocaleCatalogs["en"];
