// Generated by scripts/generate-locales.mjs. Do not edit.
export const GENERATED_LOCALE_CATALOGS = {
  "ar": {
    "feed": {
      "byAuthor": "بواسطة {author}",
      "empty": "لا توجد فيديوهات عامة حتى الآن.",
      "fallbackAuthor": "منشئ عام",
      "fallbackTitle": "فيديو عام",
      "label": "موجز الفيديو العام",
      "likeRequiresSession": "إعجاب · اتصل للتفاعل",
      "loadMore": "تحميل المزيد من الفيديوهات",
      "loadingMore": "جارٍ تحميل المزيد",
      "paginationError": "تعذر تحميل المزيد من الفيديوهات.",
      "pause": "إيقاف مؤقت",
      "play": "تشغيل",
      "retry": "إعادة المحاولة",
      "unavailable": "موجز الفيديو العام غير متاح.",
      "videoBy": "فيديو بواسطة {author}",
      "videoDescription": "وصف الفيديو",
      "videoLabel": "فيديو {title}"
    },
    "routes": {
      "home": {
        "description": "موجز فيديو بايرت ويب",
        "heading": "واجهة بايرت ويب",
        "title": "الرئيسية · بايرت ويب"
      },
      "notFound": {
        "description": "المسار المطلوب غير موجود.",
        "returnHome": "العودة إلى الرئيسية",
        "title": "غير موجود"
      },
      "profile": {
        "createdCommunities": "المجتمعات التي تم إنشاؤها",
        "createdCommunityPluralDescription": "أنشأ {name} عدد {count} من المجتمعات على Pirate Web.",
        "createdCommunitySingularDescription": "أنشأ {name} مجتمعًا واحدًا على Pirate Web.",
        "defaultDescription": "الملف الشخصي العام لـ {name} على Pirate Web.",
        "emptyCommunities": "لم يتم إنشاء مجتمعات بعد.",
        "error": "الملف الشخصي غير متاح مؤقتًا.",
        "heading": "الملف الشخصي: @{handle}",
        "invalid": "اسم الملف الشخصي غير صالح.",
        "loading": "جارٍ تحميل الملف الشخصي",
        "notFound": "تعذر العثور على هذا الملف الشخصي.",
        "openCommunity": "فتح {name}",
        "title": "@{handle} · بايرت ويب"
      }
    },
    "shell": {
      "appName": "بايرت ويب",
      "error": {
        "title": "واجهة التطبيق غير متاحة"
      },
      "navigation": {
        "community": "المجتمع",
        "home": "الرئيسية",
        "settings": "الإعدادات"
      }
    }
  },
  "en": {
    "feed": {
      "byAuthor": "by {author}",
      "empty": "No public videos are available yet.",
      "fallbackAuthor": "public creator",
      "fallbackTitle": "Public video",
      "label": "Public video feed",
      "likeRequiresSession": "Like · connect to act",
      "loadMore": "Load more videos",
      "loadingMore": "Loading more",
      "paginationError": "More videos could not be loaded.",
      "pause": "Pause",
      "play": "Play",
      "retry": "Retry",
      "unavailable": "The public video feed is unavailable.",
      "videoBy": "Video by {author}",
      "videoDescription": "Video description",
      "videoLabel": "{title} video"
    },
    "routes": {
      "home": {
        "description": "Pirate Web video feed",
        "heading": "Pirate Web Solid shell",
        "title": "Home · Pirate Web"
      },
      "notFound": {
        "description": "The requested route does not exist.",
        "returnHome": "Return home",
        "title": "Not found"
      },
      "profile": {
        "createdCommunities": "Created communities",
        "createdCommunityPluralDescription": "{name} created {count} communities on Pirate Web.",
        "createdCommunitySingularDescription": "{name} created 1 community on Pirate Web.",
        "defaultDescription": "Public profile for {name} on Pirate Web.",
        "emptyCommunities": "No communities created yet.",
        "error": "This profile is temporarily unavailable.",
        "heading": "Profile: @{handle}",
        "invalid": "That profile handle is not valid.",
        "loading": "Loading profile",
        "notFound": "This profile could not be found.",
        "openCommunity": "Open {name}",
        "title": "@{handle} · Pirate Web"
      }
    },
    "shell": {
      "appName": "Pirate Web",
      "error": {
        "title": "App shell unavailable"
      },
      "navigation": {
        "community": "Community",
        "home": "Home",
        "settings": "Settings"
      }
    }
  },
  "zh": {
    "feed": {
      "byAuthor": "作者：{author}",
      "empty": "暂时没有公开视频。",
      "fallbackAuthor": "公开视频作者",
      "fallbackTitle": "公开视频",
      "label": "公开视频动态",
      "likeRequiresSession": "点赞 · 登录后操作",
      "loadMore": "加载更多视频",
      "loadingMore": "正在加载更多",
      "paginationError": "无法加载更多视频。",
      "pause": "暂停",
      "play": "播放",
      "retry": "重试",
      "unavailable": "公开视频动态暂不可用。",
      "videoBy": "{author} 的视频",
      "videoDescription": "视频描述",
      "videoLabel": "{title} 视频"
    },
    "routes": {
      "home": {
        "description": "Pirate Web 视频动态",
        "heading": "Pirate Web Solid 界面",
        "title": "首页 · Pirate Web"
      },
      "notFound": {
        "description": "请求的页面不存在。",
        "returnHome": "返回首页",
        "title": "未找到"
      },
      "profile": {
        "createdCommunities": "已创建的社区",
        "createdCommunityPluralDescription": "{name} 在 Pirate Web 创建了 {count} 个社区。",
        "createdCommunitySingularDescription": "{name} 在 Pirate Web 创建了 1 个社区。",
        "defaultDescription": "{name} 在 Pirate Web 的公开个人资料。",
        "emptyCommunities": "尚未创建社区。",
        "error": "该个人资料暂时不可用。",
        "heading": "个人资料：@{handle}",
        "invalid": "该个人资料句柄无效。",
        "loading": "正在加载个人资料",
        "notFound": "找不到该个人资料。",
        "openCommunity": "打开 {name}",
        "title": "@{handle} · Pirate Web"
      }
    },
    "shell": {
      "appName": "Pirate Web",
      "error": {
        "title": "应用界面暂不可用"
      },
      "navigation": {
        "community": "社区",
        "home": "首页",
        "settings": "设置"
      }
    }
  }
} as const;

export type GeneratedLocaleCatalogs = typeof GENERATED_LOCALE_CATALOGS;
export type RealLocaleCode = keyof GeneratedLocaleCatalogs;
export type LocaleNamespace = keyof GeneratedLocaleCatalogs["en"];
